; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .rodata
icn_str_0:  db  72, 101, 108, 108, 111, 44, 32, 87, 111, 114, 108, 100, 33, 0

section .bss
    icn_retval: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos
    extern icn_str_cmp
    extern icn_strlen
    extern icn_pow
    extern icn_str_subscript
    extern icn_str_section

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure main ===
    ; CALL write  id=0
icon_1_α:
    lea     rdi, [rel icn_str_0]
    jmp     icon_0_call
icon_1_β:
    jmp     icn_main_done
icon_0_α:
    jmp     icon_1_α
icon_0_β:
    jmp     icon_1_β
icon_0_call:
    call    icn_write_str
    jmp     icn_main_done
icn_main:
    push    rbp
    mov     rbp, rsp
    jmp     icon_0_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret
