; Auto-generated by icon_emit_jvm.c — Tiny-ICON Byrd Box JVM
.bytecode 45.0
.class public sieve
.super java/lang/Object

.field public static icn_failed B
.field public static icn_suspended B
.field public static icn_suspend_id I
.field public static icn_retval_obj Ljava/lang/Object;
.field public static icn_retval J
.field public static icn_retval_str Ljava/lang/String;
.field public static icn_pv_main_sieve Ljava/util/ArrayList;
.field public static icn_pv_main_out Ljava/lang/String;
.field public static icn_gvar_out Ljava/lang/String;
.field public static icn_6_augtemp_s Ljava/lang/String;
.field public static icn_8_relop_lc J
.field public static icn_8_relop_rc J
.field public static icn_pv_main_i J
.field public static icn_12_augtemp_s Ljava/lang/String;
.field public static icn_14_relop_lc J
.field public static icn_14_relop_rc J
.field public static icn_16_lsub_l Ljava/util/ArrayList;
.field public static icn_16_lsub_i I
.field public static icn_20_I J
.field public static icn_20_bound J
.field public static icn_20_e1cur J
.field public static icn_20_e2seen I
.field public static icn_20_e1val J
.field public static icn_20_e2val J
.field public static icn_pv_main_limit J
.field public static icn_30_lsa_l Ljava/util/ArrayList;
.field public static icn_30_lsa_i J
.field public static icn_30_lsa_v J
.field public static icn_pv_main_j J
.field public static icn_33_toby_i J
.field public static icn_33_toby_end J
.field public static icn_33_toby_stp J
.field public static icn_34_binop_lc J
.field public static icn_34_binop_rc J
.field public static icn_34_binop_bf I
.field public static icn_39_relop_lc J
.field public static icn_39_relop_rc J
.field public static icn_41_lsub_l Ljava/util/ArrayList;
.field public static icn_41_lsub_i I
.field public static icn_45_I J
.field public static icn_45_bound J
.field public static icn_45_e1cur J
.field public static icn_45_e2seen I
.field public static icn_45_e1val J
.field public static icn_45_e2val J
.field public static icn_50_lsa_l Ljava/util/ArrayList;
.field public static icn_50_lsa_i J
.field public static icn_50_lsa_v J
.field public static icn_53_ln J
.field public static icn_53_lx Ljava/lang/Object;
.field public static icn_53_ll Ljava/util/ArrayList;
.field public static icn_53_lc I

.method public static main([Ljava/lang/String;)V
    .limit stack 4
    .limit locals 1
    invokestatic sieve/icn_main()V
    return
.end method

.method public static icn_builtin_left(Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;
    .limit stack 4
    .limit locals 5
    aload_0
    invokevirtual java/lang/String/length()I
    iload_1
    if_icmplt icn_left_pad
    aload_0
    iconst_0
    iload_1
    invokevirtual java/lang/String/substring(II)Ljava/lang/String;
    areturn
icn_left_pad:
    new java/lang/StringBuilder
    dup
    aload_0
    invokespecial java/lang/StringBuilder/<init>(Ljava/lang/String;)V
    astore_3
icn_left_loop:
    aload_3
    invokevirtual java/lang/StringBuilder/length()I
    iload_1
    if_icmpge icn_left_done
    aload_3
    aload_2
    iconst_0
    invokevirtual java/lang/String/charAt(I)C
    invokevirtual java/lang/StringBuilder/append(C)Ljava/lang/StringBuilder;
    pop
    goto icn_left_loop
icn_left_done:
    aload_3
    invokevirtual java/lang/StringBuilder/toString()Ljava/lang/String;
    areturn
.end method

.method public static icn_builtin_right(Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;
    .limit stack 4
    .limit locals 5
    aload_0
    invokevirtual java/lang/String/length()I
    iload_1
    if_icmplt icn_right_pad
    aload_0
    invokevirtual java/lang/String/length()I
    iload_1
    isub
    aload_0
    swap
    invokevirtual java/lang/String/substring(I)Ljava/lang/String;
    areturn
icn_right_pad:
    new java/lang/StringBuilder
    dup
    invokespecial java/lang/StringBuilder/<init>()V
    astore_3
    iload_1
    aload_0
    invokevirtual java/lang/String/length()I
    isub
    istore 4
    iconst_0
icn_right_loop:
    dup
    iload 4
    if_icmpge icn_right_append
    aload_3
    aload_2
    iconst_0
    invokevirtual java/lang/String/charAt(I)C
    invokevirtual java/lang/StringBuilder/append(C)Ljava/lang/StringBuilder;
    pop
    iconst_1
    iadd
    goto icn_right_loop
icn_right_append:
    pop
    aload_3
    aload_0
    invokevirtual java/lang/StringBuilder/append(Ljava/lang/String;)Ljava/lang/StringBuilder;
    pop
    aload_3
    invokevirtual java/lang/StringBuilder/toString()Ljava/lang/String;
    areturn
.end method

.method public static icn_builtin_center(Ljava/lang/String;ILjava/lang/String;)Ljava/lang/String;
    .limit stack 5
    .limit locals 7
    aload_0
    invokevirtual java/lang/String/length()I
    iload_1
    if_icmplt icn_ctr_pad
    aload_0
    iconst_0
    iload_1
    invokevirtual java/lang/String/substring(II)Ljava/lang/String;
    areturn
icn_ctr_pad:
    iload_1
    aload_0
    invokevirtual java/lang/String/length()I
    isub
    istore_3
    iload_3
    iconst_2
    idiv
    istore 4
    iload_3
    iload 4
    isub
    istore 5
    new java/lang/StringBuilder
    dup
    invokespecial java/lang/StringBuilder/<init>()V
    astore 6
    iconst_0
icn_ctr_lloop:
    dup
    iload 4
    if_icmpge icn_ctr_mid
    aload 6
    aload_2
    iconst_0
    invokevirtual java/lang/String/charAt(I)C
    invokevirtual java/lang/StringBuilder/append(C)Ljava/lang/StringBuilder;
    pop
    iconst_1
    iadd
    goto icn_ctr_lloop
icn_ctr_mid:
    pop
    aload 6
    aload_0
    invokevirtual java/lang/StringBuilder/append(Ljava/lang/String;)Ljava/lang/StringBuilder;
    pop
    iconst_0
icn_ctr_rloop:
    dup
    iload 5
    if_icmpge icn_ctr_done
    aload 6
    aload_2
    iconst_0
    invokevirtual java/lang/String/charAt(I)C
    invokevirtual java/lang/StringBuilder/append(C)Ljava/lang/StringBuilder;
    pop
    iconst_1
    iadd
    goto icn_ctr_rloop
icn_ctr_done:
    pop
    aload 6
    invokevirtual java/lang/StringBuilder/toString()Ljava/lang/String;
    areturn
.end method

.method public static icn_builtin_trim(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    .limit stack 4
    .limit locals 3
    aload_0
    invokevirtual java/lang/String/length()I
    istore_2
icn_trim_loop:
    iload_2
    ifle icn_trim_done
    aload_1
    aload_0
    iload_2
    iconst_1
    isub
    invokevirtual java/lang/String/charAt(I)C
    invokevirtual java/lang/String/indexOf(I)I
    iflt icn_trim_done
    iinc 2 -1
    goto icn_trim_loop
icn_trim_done:
    aload_0
    iconst_0
    iload_2
    invokevirtual java/lang/String/substring(II)Ljava/lang/String;
    areturn
.end method

.method public static icn_builtin_map(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    .limit stack 5
    .limit locals 7
    new java/lang/StringBuilder
    dup
    invokespecial java/lang/StringBuilder/<init>()V
    astore_3
    iconst_0
    istore 4
icn_map_loop:
    iload 4
    aload_0
    invokevirtual java/lang/String/length()I
    if_icmpge icn_map_done
    aload_0
    iload 4
    invokevirtual java/lang/String/charAt(I)C
    istore 5
    aload_1
    iload 5
    invokevirtual java/lang/String/indexOf(I)I
    istore 6
    iload 6
    iflt icn_map_notfound
    iload 6
    aload_2
    invokevirtual java/lang/String/length()I
    if_icmpge icn_map_notfound
    aload_3
    aload_2
    iload 6
    invokevirtual java/lang/String/charAt(I)C
    invokevirtual java/lang/StringBuilder/append(C)Ljava/lang/StringBuilder;
    pop
    goto icn_map_next
icn_map_notfound:
    aload_3
    iload 5
    invokevirtual java/lang/StringBuilder/append(C)Ljava/lang/StringBuilder;
    pop
icn_map_next:
    iinc 4 1
    goto icn_map_loop
icn_map_done:
    aload_3
    invokevirtual java/lang/StringBuilder/toString()Ljava/lang/String;
    areturn
.end method

.method public static icn_builtin_parse_long(Ljava/lang/String;)J
    .limit stack 4
    .limit locals 4
    .catch java/lang/Exception from icn_plong_L0 to icn_plong_L1 using icn_plong_catch
icn_plong_L0:
    aload_0
    invokevirtual java/lang/String/trim()Ljava/lang/String;
    astore_1
    aload_1
    ldc "r"
    invokevirtual java/lang/String/contains(Ljava/lang/CharSequence;)Z
    ifeq icn_plong_plain
    aload_1
    ldc "r"
    iconst_2
    invokevirtual java/lang/String/split(Ljava/lang/String;I)[Ljava/lang/String;
    astore_2
    aload_2
    iconst_0
    aaload
    invokestatic java/lang/Integer/parseInt(Ljava/lang/String;)I
    istore_3
    aload_2
    iconst_1
    aaload
    iload_3
    invokestatic java/lang/Long/parseLong(Ljava/lang/String;I)J
    goto icn_plong_L1
icn_plong_plain:
    aload_1
    invokestatic java/lang/Long/parseLong(Ljava/lang/String;)J
icn_plong_L1:
    lreturn
icn_plong_catch:
    pop
    ldc2_w -9223372036854775808
    lreturn
.end method

.method public static icn_builtin_numeric(Ljava/lang/String;)J
    .limit stack 2
    .limit locals 2
    aload_0
    invokestatic sieve/icn_builtin_parse_long(Ljava/lang/String;)J
    lreturn
.end method

.method public static icn_builtin_sort(Ljava/util/ArrayList;)Ljava/util/ArrayList;
    .limit stack 6
    .limit locals 8
    new java/util/ArrayList
    dup
    aload_0
    invokespecial java/util/ArrayList/<init>(Ljava/util/Collection;)V
    astore_1
    iconst_1
    istore_2
icn_sort_outer:
    aload_1
    invokevirtual java/util/ArrayList/size()I
    iload_2
    if_icmple icn_sort_done
    aload_1
    iload_2
    invokevirtual java/util/ArrayList/get(I)Ljava/lang/Object;
    checkcast java/lang/Long
    invokevirtual java/lang/Long/longValue()J
    lstore 4
    iload_2
    iconst_1
    isub
    istore_3
icn_sort_inner:
    iload_3
    iflt icn_sort_insert
    aload_1
    iload_3
    invokevirtual java/util/ArrayList/get(I)Ljava/lang/Object;
    checkcast java/lang/Long
    invokevirtual java/lang/Long/longValue()J
    lload 4
    lcmp
    ifle icn_sort_insert
    aload_1
    iload_3
    iconst_1
    iadd
    aload_1
    iload_3
    invokevirtual java/util/ArrayList/get(I)Ljava/lang/Object;
    invokevirtual java/util/ArrayList/set(ILjava/lang/Object;)Ljava/lang/Object;
    pop
    iinc 3 -1
    goto icn_sort_inner
icn_sort_insert:
    aload_1
    iload_3
    iconst_1
    iadd
    lload 4
    invokestatic java/lang/Long/valueOf(J)Ljava/lang/Long;
    invokevirtual java/util/ArrayList/set(ILjava/lang/Object;)Ljava/lang/Object;
    pop
    iinc 2 1
    goto icn_sort_outer
icn_sort_done:
    aload_1
    areturn
.end method

.method public static icn_builtin_sortf(Ljava/util/ArrayList;I)Ljava/util/ArrayList;
    .limit stack 8
    .limit locals 10
    new java/util/ArrayList
    dup
    aload_0
    invokespecial java/util/ArrayList/<init>(Ljava/util/Collection;)V
    astore_2
    iconst_1
    istore_3
icn_sortf_outer:
    aload_2
    invokevirtual java/util/ArrayList/size()I
    iload_3
    if_icmple icn_sortf_done
    aload_2
    iload_3
    invokevirtual java/util/ArrayList/get(I)Ljava/lang/Object;
    astore 5
    iload_3
    iconst_1
    isub
    istore 4
icn_sortf_inner:
    iload 4
    iflt icn_sortf_insert
    aload_2
    iload 4
    invokevirtual java/util/ArrayList/get(I)Ljava/lang/Object;
    astore 6
    aload 6
    invokevirtual java/lang/Object/getClass()Ljava/lang/Class;
    invokevirtual java/lang/Class/getDeclaredFields()[Ljava/lang/reflect/Field;
    iload_1
    iconst_1
    isub
    aaload
    aload 6
    invokevirtual java/lang/reflect/Field/get(Ljava/lang/Object;)Ljava/lang/Object;
    astore 7
    aload 5
    invokevirtual java/lang/Object/getClass()Ljava/lang/Class;
    invokevirtual java/lang/Class/getDeclaredFields()[Ljava/lang/reflect/Field;
    iload_1
    iconst_1
    isub
    aaload
    aload 5
    invokevirtual java/lang/reflect/Field/get(Ljava/lang/Object;)Ljava/lang/Object;
    astore 8
    aload 7
    checkcast java/lang/Long
    aload 8
    checkcast java/lang/Long
    invokevirtual java/lang/Long/compareTo(Ljava/lang/Long;)I
    ifle icn_sortf_insert
    aload_2
    iload 4
    iconst_1
    iadd
    aload_2
    iload 4
    invokevirtual java/util/ArrayList/get(I)Ljava/lang/Object;
    invokevirtual java/util/ArrayList/set(ILjava/lang/Object;)Ljava/lang/Object;
    pop
    iinc 4 -1
    goto icn_sortf_inner
icn_sortf_insert:
    aload_2
    iload 4
    iconst_1
    iadd
    aload 5
    invokevirtual java/util/ArrayList/set(ILjava/lang/Object;)Ljava/lang/Object;
    pop
    iinc 3 1
    goto icn_sortf_outer
icn_sortf_done:
    aload_2
    areturn
.end method

.method public static icn_main()V
    .limit stack 16
    .limit locals 255
    lconst_0
    lstore 0
    lconst_0
    lstore 2
    lconst_0
    lstore 4
    lconst_0
    lstore 6
    lconst_0
    lstore 8
    lconst_0
    lstore 10
    lconst_0
    lstore 12
    lconst_0
    lstore 14
    lconst_0
    lstore 16
    lconst_0
    lstore 18
    lconst_0
    lstore 20
    lconst_0
    lstore 22
    lconst_0
    lstore 24
    lconst_0
    lstore 26
    lconst_0
    lstore 28
    lconst_0
    lstore 30
    lconst_0
    lstore 32
    lconst_0
    lstore 34
    lconst_0
    lstore 36
    lconst_0
    lstore 38
    lconst_0
    lstore 40
    lconst_0
    lstore 42
    lconst_0
    lstore 44
    lconst_0
    lstore 46
    lconst_0
    lstore 48
    lconst_0
    lstore 50
    lconst_0
    lstore 52
    lconst_0
    lstore 54
    lconst_0
    lstore 56
    lconst_0
    lstore 58
    lconst_0
    lstore 60
    lconst_0
    lstore 62
    iconst_0
    istore 84
    iconst_0
    istore 85
    iconst_0
    istore 86
    iconst_0
    istore 87
    iconst_0
    istore 88
    iconst_0
    istore 89
    aconst_null
    astore 148
    aconst_null
    astore 149
    aconst_null
    astore 150
    aconst_null
    astore 151
    aconst_null
    astore 152
    goto icn_56_α
;  VAR
icn_1_α:
    getstatic sieve/icn_pv_main_out Ljava/lang/String;
    goto icn_0_waft_0
icn_1_β:
    goto icn_main_done
icn_0_α:
    goto icn_1_α
icn_0_β:
    goto icn_1_β
    goto icn_0_wentry
icn_0_waft_0:
    astore 148
    getstatic java/lang/System/out Ljava/io/PrintStream;
    aload 148
    invokevirtual java/io/PrintStream/print(Ljava/lang/String;)V
    getstatic java/lang/System/out Ljava/io/PrintStream;
    ldc ""
    invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
    aload 148
    goto icn_main_s6_sdrain
icn_0_wentry:
    goto icn_1_α
icn_main_s6_sdrain:
    pop
    goto icn_main_done
;  STR
icn_7_α:
    ldc " "
    goto icn_6_rhsok
icn_7_β:
    goto icn_4_seq_rf_0
icn_6_α:
    goto icn_7_α
icn_6_β:
    goto icn_7_β
icn_6_rhsok:
    putstatic sieve/icn_6_augtemp_s Ljava/lang/String;
    getstatic sieve/icn_pv_main_out Ljava/lang/String;
    getstatic sieve/icn_6_augtemp_s Ljava/lang/String;
    invokevirtual java/lang/String/concat(Ljava/lang/String;)Ljava/lang/String;
    dup
    putstatic sieve/icn_pv_main_out Ljava/lang/String;
    goto icn_4_seq_rg_0
;  INT
icn_9_α:
    ldc2_w 0
    goto icn_8_rrelay
icn_9_β:
    goto icn_8_lb
;  VAR
icn_11_α:
    getstatic sieve/icn_pv_main_out Ljava/lang/String;
    goto icn_10_relay
icn_11_β:
    goto icn_5_else
icn_10_α:
    goto icn_11_α
icn_10_β:
    goto icn_11_β
icn_10_relay:
    invokevirtual java/lang/String/length()I
    i2l
    goto icn_8_lrelay
icn_8_lrelay:
    putstatic sieve/icn_8_relop_lc J
    goto icn_8_lstore
icn_8_rrelay:
    putstatic sieve/icn_8_relop_rc J
    goto icn_8_check
icn_8_lb:
    goto icn_10_β
icn_8_α:
    goto icn_10_α
icn_8_β:
    goto icn_9_β
icn_8_lstore:
    goto icn_9_α
icn_8_check:
    getstatic sieve/icn_8_relop_lc J
    getstatic sieve/icn_8_relop_rc J
    lcmp
    ifle icn_9_β
    getstatic sieve/icn_8_relop_rc J
    goto icn_5_then
icn_5_then:
    pop2
    goto icn_6_α
icn_5_else:
    goto icn_4_seq_rf_0
icn_5_α:
    goto icn_8_α
icn_5_β:
    goto icn_8_β
;  VAR
icn_13_α:
    getstatic sieve/icn_pv_main_i J
    goto icn_12_rhsok
icn_13_β:
    goto icn_2_pump
icn_12_α:
    goto icn_13_α
icn_12_β:
    goto icn_13_β
icn_12_rhsok:
    invokestatic java/lang/Long/toString(J)Ljava/lang/String;
    putstatic sieve/icn_12_augtemp_s Ljava/lang/String;
    getstatic sieve/icn_pv_main_out Ljava/lang/String;
    getstatic sieve/icn_12_augtemp_s Ljava/lang/String;
    invokevirtual java/lang/String/concat(Ljava/lang/String;)Ljava/lang/String;
    dup
    putstatic sieve/icn_pv_main_out Ljava/lang/String;
    goto icn_2_bdrain
    goto icn_4_α
icn_4_seq_rg_0:
    pop
    goto icn_12_α
icn_4_seq_rf_0:
    goto icn_12_α
icn_4_α:
    goto icn_5_α
icn_4_β:
    goto icn_12_β
;  INT
icn_15_α:
    ldc2_w 1
    goto icn_14_rrelay
icn_15_β:
    goto icn_14_lb
;  VAR
icn_17_α:
    getstatic sieve/icn_pv_main_sieve Ljava/util/ArrayList;
    goto icn_16_lsub_lr
icn_17_β:
    goto icn_3_else
;  VAR
icn_18_α:
    getstatic sieve/icn_pv_main_i J
    goto icn_16_lsub_ir
icn_18_β:
    goto icn_3_else
icn_16_α:
    goto icn_17_α
icn_16_β:
    goto icn_18_β
icn_16_lsub_lr:
    putstatic sieve/icn_16_lsub_l Ljava/util/ArrayList;
    goto icn_18_α
icn_16_lsub_ir:
    l2i
    istore 84
    iload 84
    ifgt icn_16_lsub_pos
    iload 84
    iflt icn_16_lsub_neg
icn_16_lsub_z:
    goto icn_3_else
icn_16_lsub_pos:
    iload 84
    iconst_1
    isub
    putstatic sieve/icn_16_lsub_i I
    goto icn_16_lsub_chk
icn_16_lsub_neg:
    getstatic sieve/icn_16_lsub_l Ljava/util/ArrayList;
    invokevirtual java/util/ArrayList/size()I
    iload 84
    iadd
    putstatic sieve/icn_16_lsub_i I
    goto icn_16_lsub_chk
icn_16_lsub_chk:
    getstatic sieve/icn_16_lsub_i I
    iflt icn_3_else
    getstatic sieve/icn_16_lsub_l Ljava/util/ArrayList;
    invokevirtual java/util/ArrayList/size()I
    getstatic sieve/icn_16_lsub_i I
    if_icmple icn_3_else
    getstatic sieve/icn_16_lsub_l Ljava/util/ArrayList;
    getstatic sieve/icn_16_lsub_i I
    invokevirtual java/util/ArrayList/get(I)Ljava/lang/Object;
    checkcast java/lang/Long
    invokevirtual java/lang/Long/longValue()J
    goto icn_14_lrelay
icn_14_lrelay:
    putstatic sieve/icn_14_relop_lc J
    goto icn_14_lstore
icn_14_rrelay:
    putstatic sieve/icn_14_relop_rc J
    goto icn_14_check
icn_14_lb:
    goto icn_16_β
icn_14_α:
    goto icn_16_α
icn_14_β:
    goto icn_15_β
icn_14_lstore:
    goto icn_15_α
icn_14_check:
    getstatic sieve/icn_14_relop_lc J
    getstatic sieve/icn_14_relop_rc J
    lcmp
    ifne icn_15_β
    getstatic sieve/icn_14_relop_rc J
    goto icn_3_then
icn_3_then:
    pop2
    goto icn_4_α
icn_3_else:
    goto icn_2_pump
icn_3_α:
    goto icn_14_α
icn_3_β:
    goto icn_14_β
;  VAR
icn_21_α:
    getstatic sieve/icn_pv_main_limit J
    goto icn_20_e2relay
icn_21_β:
    goto icn_20_e1b
;  INT
icn_22_α:
    ldc2_w 2
    goto icn_20_e1relay
icn_22_β:
    goto icn_0_α
icn_20_e1relay:
    putstatic sieve/icn_20_e1val J
    goto icn_21_α
icn_20_e2relay:
    putstatic sieve/icn_20_e2val J
    goto icn_20_init
icn_20_e1b:
    iconst_0
    putstatic sieve/icn_20_e2seen I
    goto icn_22_β
icn_20_e2b:
    goto icn_21_β
icn_20_α:
    iconst_0
    putstatic sieve/icn_20_e2seen I
    goto icn_22_α
icn_20_β:
    getstatic sieve/icn_20_I J
    lconst_1
    ladd
    putstatic sieve/icn_20_I J
    goto icn_20_code
icn_20_init:
    getstatic sieve/icn_20_e2val J
    putstatic sieve/icn_20_bound J
    getstatic sieve/icn_20_e2seen I
    ifne icn_20_init_e2adv
    getstatic sieve/icn_20_e1val J
    putstatic sieve/icn_20_e1cur J
    getstatic sieve/icn_20_e1cur J
    putstatic sieve/icn_20_I J
    iconst_1
    putstatic sieve/icn_20_e2seen I
    goto icn_20_code
icn_20_init_e2adv:
    getstatic sieve/icn_20_e1cur J
    putstatic sieve/icn_20_I J
    goto icn_20_code
icn_20_code:
    getstatic sieve/icn_20_I J
    getstatic sieve/icn_20_bound J
    lcmp
    ifgt icn_20_e2b
    getstatic sieve/icn_20_I J
    goto icn_19_store
icn_19_α:
    goto icn_20_α
icn_19_β:
    goto icn_20_β
icn_19_store:
    putstatic sieve/icn_pv_main_i J
    getstatic sieve/icn_pv_main_i J
    goto icn_2_gdrain
icn_2_gdrain:
    pop2
    goto icn_3_α
icn_2_bdrain:
    pop
icn_2_pump:
    goto icn_19_β
icn_2_α:
    goto icn_19_α
icn_2_β:
    goto icn_0_α
;  STR
icn_24_α:
    ldc ""
    goto icn_23_store
icn_24_β:
    goto icn_2_α
icn_23_α:
    goto icn_24_α
icn_23_β:
    goto icn_24_β
icn_23_store:
    putstatic sieve/icn_pv_main_out Ljava/lang/String;
    getstatic sieve/icn_pv_main_out Ljava/lang/String;
    goto icn_main_s4_sdrain
icn_main_s4_sdrain:
    pop
    goto icn_2_α
;  INT
icn_29_α:
    ldc2_w 0
    goto icn_28_store
icn_29_β:
    goto icn_27_pump
icn_28_α:
    goto icn_29_α
icn_28_β:
    goto icn_29_β
icn_28_store:
    putstatic sieve/icn_30_lsa_v J
    getstatic sieve/icn_pv_main_sieve Ljava/util/ArrayList;
    putstatic sieve/icn_30_lsa_l Ljava/util/ArrayList;
;  VAR
icn_31_α:
    getstatic sieve/icn_pv_main_j J
    goto icn_30_lsa_ir
icn_31_β:
    goto icn_27_pump
    goto icn_31_α
icn_30_lsa_ir:
    lconst_1
    lsub
    putstatic sieve/icn_30_lsa_i J
    goto icn_30_lsa_do
icn_30_lsa_do:
    getstatic sieve/icn_30_lsa_l Ljava/util/ArrayList;
    getstatic sieve/icn_30_lsa_i J
    l2i
    getstatic sieve/icn_30_lsa_v J
    invokestatic java/lang/Long/valueOf(J)Ljava/lang/Long;
    invokevirtual java/util/ArrayList/set(ILjava/lang/Object;)Ljava/lang/Object;
    pop
    getstatic sieve/icn_30_lsa_v J
    goto icn_27_bdrain
;  VAR
icn_35_α:
    getstatic sieve/icn_pv_main_i J
    goto icn_34_rrelay
icn_35_β:
    goto icn_34_lb
;  VAR
icn_36_α:
    getstatic sieve/icn_pv_main_i J
    goto icn_34_lrelay
icn_36_β:
    goto icn_25_pump
icn_34_lrelay:
    putstatic sieve/icn_34_binop_lc J
    goto icn_34_lstore
icn_34_rrelay:
    putstatic sieve/icn_34_binop_rc J
    goto icn_34_compute
icn_34_lb:
    goto icn_36_β
icn_34_α:
    iconst_0
    putstatic sieve/icn_34_binop_bf I
    goto icn_36_α
icn_34_β:
    iconst_1
    putstatic sieve/icn_34_binop_bf I
    goto icn_36_α
icn_34_lstore:
    getstatic sieve/icn_34_binop_bf I
    ifeq icn_35_α
    goto icn_35_β
icn_34_compute:
    getstatic sieve/icn_34_binop_lc J
    getstatic sieve/icn_34_binop_rc J
    lmul
    goto icn_33_tb_r1
;  VAR
icn_37_α:
    getstatic sieve/icn_pv_main_limit J
    goto icn_33_tb_r2
icn_37_β:
    goto icn_25_pump
;  VAR
icn_38_α:
    getstatic sieve/icn_pv_main_i J
    goto icn_33_tb_r3
icn_38_β:
    goto icn_25_pump
;  TO_BY -- forward-only, supports integer and real
icn_33_α:
    goto icn_34_α
icn_33_tb_r1:
    putstatic sieve/icn_33_toby_i J
    goto icn_37_α
icn_33_tb_r2:
    putstatic sieve/icn_33_toby_end J
    goto icn_38_α
icn_33_tb_r3:
    putstatic sieve/icn_33_toby_stp J
    goto icn_33_tb_check
icn_33_β:
    getstatic sieve/icn_33_toby_i J
    getstatic sieve/icn_33_toby_stp J
    ladd
    putstatic sieve/icn_33_toby_i J
    goto icn_33_tb_check
icn_33_tb_check:
    getstatic sieve/icn_33_toby_stp J
    lconst_0
    lcmp
    ifgt icn_33_tb_ckp
    getstatic sieve/icn_33_toby_stp J
    lconst_0
    lcmp
    iflt icn_33_tb_ckn
    goto icn_25_pump
icn_33_tb_ckp:
    getstatic sieve/icn_33_toby_i J
    getstatic sieve/icn_33_toby_end J
    lcmp
    ifgt icn_25_pump
    getstatic sieve/icn_33_toby_i J
    goto icn_32_store
icn_33_tb_ckn:
    getstatic sieve/icn_33_toby_i J
    getstatic sieve/icn_33_toby_end J
    lcmp
    iflt icn_25_pump
    getstatic sieve/icn_33_toby_i J
    goto icn_32_store
icn_32_α:
    goto icn_33_α
icn_32_β:
    goto icn_33_β
icn_32_store:
    putstatic sieve/icn_pv_main_j J
    getstatic sieve/icn_pv_main_j J
    goto icn_27_gdrain
icn_27_gdrain:
    pop2
    goto icn_28_α
icn_27_bdrain:
    pop2
icn_27_pump:
    goto icn_32_β
icn_27_α:
    goto icn_32_α
icn_27_β:
    goto icn_25_pump
;  INT
icn_40_α:
    ldc2_w 1
    goto icn_39_rrelay
icn_40_β:
    goto icn_39_lb
;  VAR
icn_42_α:
    getstatic sieve/icn_pv_main_sieve Ljava/util/ArrayList;
    goto icn_41_lsub_lr
icn_42_β:
    goto icn_26_else
;  VAR
icn_43_α:
    getstatic sieve/icn_pv_main_i J
    goto icn_41_lsub_ir
icn_43_β:
    goto icn_26_else
icn_41_α:
    goto icn_42_α
icn_41_β:
    goto icn_43_β
icn_41_lsub_lr:
    putstatic sieve/icn_41_lsub_l Ljava/util/ArrayList;
    goto icn_43_α
icn_41_lsub_ir:
    l2i
    istore 85
    iload 85
    ifgt icn_41_lsub_pos
    iload 85
    iflt icn_41_lsub_neg
icn_41_lsub_z:
    goto icn_26_else
icn_41_lsub_pos:
    iload 85
    iconst_1
    isub
    putstatic sieve/icn_41_lsub_i I
    goto icn_41_lsub_chk
icn_41_lsub_neg:
    getstatic sieve/icn_41_lsub_l Ljava/util/ArrayList;
    invokevirtual java/util/ArrayList/size()I
    iload 85
    iadd
    putstatic sieve/icn_41_lsub_i I
    goto icn_41_lsub_chk
icn_41_lsub_chk:
    getstatic sieve/icn_41_lsub_i I
    iflt icn_26_else
    getstatic sieve/icn_41_lsub_l Ljava/util/ArrayList;
    invokevirtual java/util/ArrayList/size()I
    getstatic sieve/icn_41_lsub_i I
    if_icmple icn_26_else
    getstatic sieve/icn_41_lsub_l Ljava/util/ArrayList;
    getstatic sieve/icn_41_lsub_i I
    invokevirtual java/util/ArrayList/get(I)Ljava/lang/Object;
    checkcast java/lang/Long
    invokevirtual java/lang/Long/longValue()J
    goto icn_39_lrelay
icn_39_lrelay:
    putstatic sieve/icn_39_relop_lc J
    goto icn_39_lstore
icn_39_rrelay:
    putstatic sieve/icn_39_relop_rc J
    goto icn_39_check
icn_39_lb:
    goto icn_41_β
icn_39_α:
    goto icn_41_α
icn_39_β:
    goto icn_40_β
icn_39_lstore:
    goto icn_40_α
icn_39_check:
    getstatic sieve/icn_39_relop_lc J
    getstatic sieve/icn_39_relop_rc J
    lcmp
    ifne icn_40_β
    getstatic sieve/icn_39_relop_rc J
    goto icn_26_then
icn_26_then:
    pop2
    goto icn_27_α
icn_26_else:
    goto icn_25_pump
icn_26_α:
    goto icn_39_α
icn_26_β:
    goto icn_39_β
;  VAR
icn_46_α:
    getstatic sieve/icn_pv_main_limit J
    goto icn_45_e2relay
icn_46_β:
    goto icn_45_e1b
;  INT
icn_47_α:
    ldc2_w 2
    goto icn_45_e1relay
icn_47_β:
    goto icn_23_α
icn_45_e1relay:
    putstatic sieve/icn_45_e1val J
    goto icn_46_α
icn_45_e2relay:
    putstatic sieve/icn_45_e2val J
    goto icn_45_init
icn_45_e1b:
    iconst_0
    putstatic sieve/icn_45_e2seen I
    goto icn_47_β
icn_45_e2b:
    goto icn_46_β
icn_45_α:
    iconst_0
    putstatic sieve/icn_45_e2seen I
    goto icn_47_α
icn_45_β:
    getstatic sieve/icn_45_I J
    lconst_1
    ladd
    putstatic sieve/icn_45_I J
    goto icn_45_code
icn_45_init:
    getstatic sieve/icn_45_e2val J
    putstatic sieve/icn_45_bound J
    getstatic sieve/icn_45_e2seen I
    ifne icn_45_init_e2adv
    getstatic sieve/icn_45_e1val J
    putstatic sieve/icn_45_e1cur J
    getstatic sieve/icn_45_e1cur J
    putstatic sieve/icn_45_I J
    iconst_1
    putstatic sieve/icn_45_e2seen I
    goto icn_45_code
icn_45_init_e2adv:
    getstatic sieve/icn_45_e1cur J
    putstatic sieve/icn_45_I J
    goto icn_45_code
icn_45_code:
    getstatic sieve/icn_45_I J
    getstatic sieve/icn_45_bound J
    lcmp
    ifgt icn_45_e2b
    getstatic sieve/icn_45_I J
    goto icn_44_store
icn_44_α:
    goto icn_45_α
icn_44_β:
    goto icn_45_β
icn_44_store:
    putstatic sieve/icn_pv_main_i J
    getstatic sieve/icn_pv_main_i J
    goto icn_25_gdrain
icn_25_gdrain:
    pop2
    goto icn_26_α
icn_25_bdrain:
    pop2
icn_25_pump:
    goto icn_44_β
icn_25_α:
    goto icn_44_α
icn_25_β:
    goto icn_23_α
;  INT
icn_49_α:
    ldc2_w 0
    goto icn_48_store
icn_49_β:
    goto icn_25_α
icn_48_α:
    goto icn_49_α
icn_48_β:
    goto icn_49_β
icn_48_store:
    putstatic sieve/icn_50_lsa_v J
    getstatic sieve/icn_pv_main_sieve Ljava/util/ArrayList;
    putstatic sieve/icn_50_lsa_l Ljava/util/ArrayList;
;  INT
icn_51_α:
    ldc2_w 1
    goto icn_50_lsa_ir
icn_51_β:
    goto icn_25_α
    goto icn_51_α
icn_50_lsa_ir:
    lconst_1
    lsub
    putstatic sieve/icn_50_lsa_i J
    goto icn_50_lsa_do
icn_50_lsa_do:
    getstatic sieve/icn_50_lsa_l Ljava/util/ArrayList;
    getstatic sieve/icn_50_lsa_i J
    l2i
    getstatic sieve/icn_50_lsa_v J
    invokestatic java/lang/Long/valueOf(J)Ljava/lang/Long;
    invokevirtual java/util/ArrayList/set(ILjava/lang/Object;)Ljava/lang/Object;
    pop
    getstatic sieve/icn_50_lsa_v J
    goto icn_main_s2_sdrain
icn_main_s2_sdrain:
    pop2
    goto icn_25_α
;  VAR
icn_54_α:
    getstatic sieve/icn_pv_main_limit J
    goto icn_53_nlr
icn_54_β:
    goto icn_48_α
;  INT
icn_55_α:
    ldc2_w 1
    goto icn_53_xlr
icn_55_β:
    goto icn_48_α
icn_53_α:
    goto icn_54_α
icn_53_β:
    goto icn_48_α
icn_53_nlr:
    putstatic sieve/icn_53_ln J
    goto icn_55_α
icn_53_xlr:
    invokestatic java/lang/Long/valueOf(J)Ljava/lang/Long;
    putstatic sieve/icn_53_lx Ljava/lang/Object;
    new java/util/ArrayList
    dup
    invokespecial java/util/ArrayList/<init>()V
    putstatic sieve/icn_53_ll Ljava/util/ArrayList;
    getstatic sieve/icn_53_ln J
    l2i
    putstatic sieve/icn_53_lc I
icn_53_llp:
    getstatic sieve/icn_53_lc I
    ifeq icn_53_lld
    getstatic sieve/icn_53_ll Ljava/util/ArrayList;
    getstatic sieve/icn_53_lx Ljava/lang/Object;
    invokevirtual java/util/ArrayList/add(Ljava/lang/Object;)Z
    pop
    getstatic sieve/icn_53_lc I
    iconst_1
    isub
    putstatic sieve/icn_53_lc I
    goto icn_53_llp
icn_53_lld:
    getstatic sieve/icn_53_ll Ljava/util/ArrayList;
    goto icn_52_store
icn_52_α:
    goto icn_53_α
icn_52_β:
    goto icn_53_β
icn_52_store:
    putstatic sieve/icn_pv_main_sieve Ljava/util/ArrayList;
    getstatic sieve/icn_pv_main_sieve Ljava/util/ArrayList;
    goto icn_main_s1_sdrain
icn_main_s1_sdrain:
    pop
    goto icn_48_α
;  INT
icn_57_α:
    ldc2_w 50
    goto icn_56_store
icn_57_β:
    goto icn_52_α
icn_56_α:
    goto icn_57_α
icn_56_β:
    goto icn_57_β
icn_56_store:
    putstatic sieve/icn_pv_main_limit J
    getstatic sieve/icn_pv_main_limit J
    goto icn_main_s0_sdrain
icn_main_s0_sdrain:
    pop2
    goto icn_52_α
icn_main_done:
    return
.end method

