; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .rodata
icn_str_0:  db  116, 104, 101, 32, 113, 117, 105, 99, 107, 32, 98, 114, 111, 119, 110, 32, 102, 111, 120, 32, 106, 117, 109, 112, 115, 32, 111, 118, 101, 114, 32, 116, 104, 101, 32, 108, 97, 122, 121, 32, 100, 111, 103, 0

section .bss
    icn_retval: resq 1
    icn_gvar_count: resq 1
    icn_scan_oldsubj_2: resq 1
    icn_scan_oldpos_2: resq 1
    icn_gvar_s: resq 1
    icn_gvar_&letters: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos
    extern icn_str_cmp
    extern icn_strlen
    extern icn_pow
    extern icn_str_subscript
    extern icn_str_section

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure main ===
    ; CALL write  id=0
    ; VAR count  id=1
icon_1_α:
    mov     rax, [rel icn_gvar_count]
    push    rax
    jmp     icon_0_call
icon_1_β:
    jmp     icn_main_done
icon_0_α:
    jmp     icon_1_α
icon_0_β:
    jmp     icon_1_β
icon_0_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_main_done
    ; VAR s  id=3
icon_3_α:
    mov     rax, [rel icn_gvar_s]
    push    rax
    jmp     icon_2_scan_setup
icon_3_β:
    jmp     icon_0_α
    ; WHILE  id=4
    ; CALL tab  id=5
    ; CALL upto  id=6
    ; VAR &letters  id=7
icon_7_α:
    mov     rax, [rel icn_gvar_&letters]
    push    rax
    jmp     icon_6_sbuiltin
icon_7_β:
    jmp     icon_2_scan_bfail
icon_6_α:
    jmp     icon_7_α
icon_6_β:
    jmp     icon_7_β
icon_6_sbuiltin:
    pop     rdi
    call    icn_upto
    test    rax, rax
    jz      icon_2_scan_bfail
    push    rax
    jmp     icon_5_taft
icon_5_α:
    jmp     icon_6_α
icon_5_β:
    jmp     icon_2_scan_bfail
icon_5_taft:
    pop     rdi
    call    icn_tab
    test    rax, rax
    jz      icon_2_scan_bfail
    push    rax
    jmp     icon_4_condok
icon_4_condok:
    add     rsp, 8
    ; ADD  id=10
    ; INT 1  id=11
icon_11_α:
    push    1
    jmp     icon_10_compute
icon_11_β:
    jmp     icon_10_lb
    ; VAR count  id=12
icon_12_α:
    mov     rax, [rel icn_gvar_count]
    push    rax
    jmp     icon_10_lstore
icon_12_β:
    jmp     icon_4_top
icon_10_lb:
    jmp     icon_12_β
icon_10_α:
    mov     qword [rbp-16], 0
    jmp     icon_12_α
icon_10_β:
    mov     qword [rbp-16], 1
    jmp     icon_12_α
icon_10_lstore:
    pop     rax
    mov     [rbp-8], rax
    cmp     qword [rbp-16], 0
    je      icon_11_α
    jmp     icon_11_β
icon_10_compute:
    pop     rax
    mov     rcx, [rbp-8]
    add     rcx, rax
    push    rcx
    jmp     icon_9_aug_store
icon_9_α:
    jmp     icon_10_α
icon_9_β:
    jmp     icon_10_β
icon_9_aug_store:
    pop     rax
    mov     [rel icn_gvar_count], rax
    jmp     icon_4_top
    ; CALL tab  id=13
    ; CALL many  id=14
    ; VAR &letters  id=15
icon_15_α:
    mov     rax, [rel icn_gvar_&letters]
    push    rax
    jmp     icon_14_sbuiltin
icon_15_β:
    jmp     icon_4_top
icon_14_α:
    jmp     icon_15_α
icon_14_β:
    jmp     icon_15_β
icon_14_sbuiltin:
    pop     rdi
    call    icn_many
    test    rax, rax
    jz      icon_4_top
    push    rax
    jmp     icon_13_taft
icon_13_α:
    jmp     icon_14_α
icon_13_β:
    jmp     icon_4_top
icon_13_taft:
    pop     rdi
    call    icn_tab
    test    rax, rax
    jz      icon_4_top
    push    rax
    jmp     icon_8_seq_0
icon_8_seq_0:
    add     rsp, 8
    jmp     icon_9_α
icon_8_α:
    jmp     icon_13_α
icon_8_β:
    jmp     icon_4_top
    jmp     icon_8_α
icon_4_top:
    jmp     icon_5_α
icon_4_α:
    jmp     icon_5_α
icon_4_β:
    jmp     icon_2_scan_bfail
    ; SCAN  id=2
icon_2_α:
    jmp     icon_3_α
icon_2_β:
    jmp     icon_2_scan_bret
icon_2_scan_setup:
    pop     rax
    push    rax
    mov     rcx, [rel icn_subject]
    mov     [rel icn_scan_oldsubj_2], rcx
    mov     rcx, [rel icn_pos]
    mov     [rel icn_scan_oldpos_2], rcx
    pop     rax
    mov     [rel icn_subject], rax
    mov     qword [rel icn_pos], 0
    jmp     icon_4_α
icon_2_scan_bok:
    mov     rax, [rel icn_scan_oldsubj_2]
    mov     [rel icn_subject], rax
    mov     rax, [rel icn_scan_oldpos_2]
    mov     [rel icn_pos], rax
    jmp     icon_0_α
icon_2_scan_bfail:
    mov     rax, [rel icn_scan_oldsubj_2]
    mov     [rel icn_subject], rax
    mov     rax, [rel icn_scan_oldpos_2]
    mov     [rel icn_pos], rax
    jmp     icon_3_β
icon_2_scan_bret:
    mov     rax, [rel icn_scan_oldsubj_2]
    mov     [rel icn_subject], rax
    mov     rax, [rel icn_scan_oldpos_2]
    mov     [rel icn_pos], rax
    jmp     icon_4_β
    ; INT 0  id=17
icon_17_α:
    push    0
    jmp     icon_16_store
icon_17_β:
    jmp     icon_2_α
icon_16_α:
    jmp     icon_17_α
icon_16_β:
    jmp     icon_17_β
icon_16_store:
    pop     rax
    mov     [rel icn_gvar_count], rax
    jmp     icon_2_α
icon_19_α:
    lea     rdi, [rel icn_str_0]
    jmp     icon_18_store
icon_19_β:
    jmp     icon_16_α
icon_18_α:
    jmp     icon_19_α
icon_18_β:
    jmp     icon_19_β
icon_18_store:
    ; str assign: rdi already has pointer
    mov     [rel icn_gvar_s], rdi
    jmp     icon_16_α
icn_main:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 32
    jmp     icon_18_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 32
    pop     rbp
    ret
