; generated by sno2c -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o mock_engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var
extern  stmt_at_capture
extern  kw_anchor
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
P_ROMAN_ret_γ           resq 1
P_ROMAN_ret_ω           resq 1
fn_ROMAN_save_N_t        resq 1
fn_ROMAN_save_N_p        resq 1
fn_ROMAN_arg_0_t         resq 1
fn_ROMAN_arg_0_p         resq 1
P_T1_ret_γ              resq 1
P_T1_ret_ω              resq 1
P_R_ret_γ               resq 1
P_R_ret_ω               resq 1
P_N_ret_γ               resq 1
P_N_ret_ω               resq 1
P_T2_ret_γ              resq 1
P_T2_ret_ω              resq 1
scan_start_3             resq 1
scan_start_4             resq 1
dol_entry_T              resq 1
len2_saved               resq 1
brk5_saved               resq 1
cap_T_buf                resb 256
cap_T_len                resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
                            PROG_INIT


;  PROGRAM BODY ========================================================================================================

                            ASSIGN_INT  S_TRIM, 1, Ln_0
                            jmp         Ln_0

; ======================================================================================================================

; ======================================================================================================================
Ln_0:                       ASSIGN_INT  S_STLIMIT, 1000000000, Ln_1
                            jmp         Ln_1

Ln_1:

; ======================================================================================================================

Ln_2:
;  ROMAN ===============================================================================================================
L_ROMAN_1:                  GET_VAR     S_N
                            SUBJ_FROM16

                            mov         qword [scan_start_3], 0
scan_retry_3:
                            mov         rax, [scan_start_3]
                            mov         [cursor], rax
                            jmp         P_3_α

P_3_α:                      jmp         seq_l0_alpha ; SEQ
P_3_β:                      jmp         seq_r0_beta
seq_l0_alpha:               RPOS_ALPHA  1, cursor, subject_len_val, seq_r0_alpha, P_3_ω ; RPOS(%ld)
seq_l0_beta:                RPOS_BETA   cursor, P_3_ω

seq_r0_alpha: ; DOL(T $  T)
                            DOL_SAVE    dol_entry_T, cursor, dol1_child_alpha ; DOL α — save entry cursor
seq_r0_beta:                jmp         dol1_child_beta ; DOL β
dol1_child_alpha:           LEN_ALPHA   1, len2_saved, cursor, subject_len_val, dol1_gamma, dol1_omega ; LEN(%ld)
dol1_child_beta:            LEN_BETA    len2_saved, cursor, dol1_omega ; LEN β
dol1_gamma:                 DOL_CAPTURE dol_entry_T, cursor, cap_T_buf, cap_T_len, subject_data, P_3_γ ; DOL γ — capture span
dol1_omega:                 jmp         seq_l0_beta ; DOL ω — child failed

P_3_γ:                      SET_CAPTURE S_T, cap_T_buf, cap_T_len
                            mov         qword [rbp-32], 1
                            mov         qword [rbp-24], 0
                            APPLY_REPL_SPLICE S_N, scan_start_3
                            jmp         Ln_3
P_3_ω:                      cmp         qword [rel kw_anchor], 0
                            jne         L_RETURN_4
                            mov         rax, [scan_start_3]
                            inc         rax
                            cmp         rax, [subject_len_val]
                            jg          L_RETURN_4
                            mov         [scan_start_3], rax
                            jmp         scan_retry_3
                            jmp         [P_ROMAN_ret_γ]     ; RETURN

; ======================================================================================================================
Ln_3:                       LOAD_STR    S_0_CM_1I_CM_2II_CM_3III_CM_4IV_CM_5V_CM_6VI_CM_7VII_CM_8VIII_C
                            mov         [rbp-16], rax
                            mov         [rbp-8],  rdx
                            SUBJ_FROM16

                            mov         qword [scan_start_4], 0
scan_retry_4:
                            mov         rax, [scan_start_4]
                            mov         [cursor], rax
                            jmp         P_4_α

P_4_α:                      jmp         seq_l3_alpha ; SEQ
P_4_β:                      jmp         seq_r3_beta

; UNRESOLVED named pattern ref: T → ω
seq_l3_alpha:
seq_l3_beta:                jmp         P_4_ω

seq_r3_alpha: ; DOL(T $  T)
                            DOL_SAVE    dol_entry_T, cursor, dol4_child_alpha ; DOL α — save entry cursor
seq_r3_beta:                jmp         dol4_child_beta ; DOL β
dol4_child_alpha:           BREAK_ALPHA lit_str_1, 1, brk5_saved, cursor, subject_data, subject_len_val, dol4_gamma, dol4_omega ; BREAK α
dol4_child_beta:            BREAK_BETA  brk5_saved, cursor, dol4_omega ; BREAK β
dol4_gamma:                 DOL_CAPTURE dol_entry_T, cursor, cap_T_buf, cap_T_len, subject_data, P_4_γ ; DOL γ — capture span
dol4_omega:                 jmp         seq_l3_beta ; DOL ω — child failed

P_4_γ:                      SET_CAPTURE S_T, cap_T_buf, cap_T_len
                            jmp         Ln_4
P_4_ω:                      cmp         qword [rel kw_anchor], 0
                            jne         L_FRETURN_5
                            mov         rax, [scan_start_4]
                            inc         rax
                            cmp         rax, [subject_len_val]
                            jg          L_FRETURN_5
                            mov         [scan_start_4], rax
                            jmp         scan_retry_4
                            jmp         [P_ROMAN_ret_γ]     ; FRETURN

; ======================================================================================================================
Ln_4:                       sub         rsp, 48
                            lea         rdi, [rel S_N]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            mov         rax, [rbp-32]
                            mov         rcx, [rbp-24]
                            mov         [fn_ROMAN_arg_0_t], rax
                            mov         [fn_ROMAN_arg_0_p], rcx
                            lea         rax, [rel ucall6_ret_g]
                            mov         [P_ROMAN_ret_γ], rax
                            lea         rax, [rel ucall6_ret_o]
                            mov         [P_ROMAN_ret_ω], rax
                            jmp         P_ROMAN_α
ucall6_ret_g:
                            GET_VAR     S_ROMAN
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            jmp         ucall6_done
ucall6_ret_o:
                            LOAD_NULVCL32

ucall6_done:
                            STORE_ARG32 0
                            LOAD_STR    S_IVXLCDM
                            STORE_ARG32 16
                            LOAD_STR    S_XLCDM_ST_ST
                            STORE_ARG32 32
                            APPLY_FN_N  S_REPLACE, 3
                            add         rsp, 48
                            STORE_RESULT

                            mov         [conc_tmp0_rax], rax
                            mov         [conc_tmp0_rdx], rdx
                            lea         rdi, [rel S_T]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            mov         rcx, rdx
                            mov         rdx, rax
                            mov         rdi, [conc_tmp0_rax]
                            mov         rsi, [conc_tmp0_rdx]
                            call        stmt_concat
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Lf_5
                            SET_VAR     S_ROMAN
                            jmp         [P_ROMAN_ret_γ]     ; RETURN
Lf_5:                       jmp         [P_ROMAN_ret_γ]     ; FRETURN

Ln_5:
L_ROMAN_END_0:

;  ROMAN_END ===========================================================================================================

; ======================================================================================================================
Ln_6:                       APPLY_FN_0  S_TIME
                            STORE_RESULT

                            FAIL_BR     Ln_7
                            SET_VAR     S_T1
                            jmp         Ln_7

; ======================================================================================================================
Ln_7:                       ASSIGN_INT  S_N, 0, Ln_8
                            jmp         Ln_8

Ln_8:
;  LOOP ================================================================================================================
L_LOOP_2:                   LOAD_STR    S_1776
                            mov         rax, [rbp-32]
                            mov         rcx, [rbp-24]
                            mov         [fn_ROMAN_arg_0_t], rax
                            mov         [fn_ROMAN_arg_0_p], rcx
                            lea         rax, [rel ucall7_ret_g]
                            mov         [P_ROMAN_ret_γ], rax
                            lea         rax, [rel ucall7_ret_o]
                            mov         [P_ROMAN_ret_ω], rax
                            jmp         P_ROMAN_α
ucall7_ret_g:
                            GET_VAR     S_ROMAN
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            jmp         ucall7_done
ucall7_ret_o:
                            LOAD_NULVCL32

ucall7_done:
                            FAIL_BR     Ln_9
                            SET_VAR     S_R
                            jmp         Ln_9

; ======================================================================================================================
Ln_9:                       CONC2_VI    S_LT, S_N, 100000
                            mov         [conc_tmp0_rax], rax
                            mov         [conc_tmp0_rdx], rdx
                            CONC2_VI    S_add, S_N, 1
                            mov         rcx, rdx
                            mov         rdx, rax
                            mov         rdi, [conc_tmp0_rax]
                            mov         rsi, [conc_tmp0_rdx]
                            call        stmt_concat
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Ln_10
                            SET_VAR     S_N
                            jmp         L_LOOP_2

; ======================================================================================================================
Ln_10:                      APPLY_FN_0  S_TIME
                            STORE_RESULT

                            FAIL_BR     Ln_11
                            SET_VAR     S_T2
                            jmp         Ln_11

; ======================================================================================================================
Ln_11:                      CAT2_SV     S_result_CL_SP, S_R
                            FAIL_BR     Ln_12
                            SET_OUTPUT

                            jmp         Ln_12

; ======================================================================================================================
Ln_12:                      LOAD_STR    S_ms_CL_SP
                            mov         [conc_tmp0_rax], rax
                            mov         [conc_tmp0_rdx], rdx
                            CONC2_VV    S_sub, S_T2, S_T1
                            mov         rcx, rdx
                            mov         rdx, rax
                            mov         rdi, [conc_tmp0_rax]
                            mov         rsi, [conc_tmp0_rdx]
                            call        stmt_concat
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Ln_13
                            SET_OUTPUT

                            jmp         Ln_13
Ln_13:                      GOTO_ALWAYS L_SNO_END

L_SNO_END:
                            PROG_END


section .data
lit_str_1            db 44
;  END =================================================================================================================

section .text

;  NAMED PATTERN BODIES ================================================================================================

; P_ROMAN_α — user function α entry (1 param)
;  ROMAN ===============================================================================================================
P_ROMAN_α:                  GET_VAR     S_N
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            mov         [fn_ROMAN_save_N_t], rax
                            mov         [fn_ROMAN_save_N_p], rdx
                            lea         rdi, [rel S_N]
                            mov         rsi, [fn_ROMAN_arg_0_t]
                            mov         rdx, [fn_ROMAN_arg_0_p]
                            call        stmt_set
                            jmp         L_ROMAN_1
;  γ/ω ---------------------------------------------------------------------------------------------------------------
fn_ROMAN_gamma:             lea         rdi, [rel S_N]
                            mov         rsi, [fn_ROMAN_save_N_t]
                            mov         rdx, [fn_ROMAN_save_N_p]
                            call        stmt_set
                            jmp         [P_ROMAN_ret_γ]
fn_ROMAN_omega:             lea         rdi, [rel S_N]
                            mov         rsi, [fn_ROMAN_save_N_t]
                            mov         rdx, [fn_ROMAN_save_N_p]
                            call        stmt_set
                            jmp         [P_ROMAN_ret_ω]

; P_T1_α (α entry)

; UNIMPLEMENTED: TIME() → ω
P_T1_α:
P_T1_β:                     jmp         patdef_T1_omega
;  γ/ω ---------------------------------------------------------------------------------------------------------------
patdef_T1_gamma:
                            jmp         [P_T1_ret_γ]
;  T1 ==================================================================================================================
patdef_T1_omega:            jmp         [P_T1_ret_ω]

; P_R_α (α entry)

; UNIMPLEMENTED: ROMAN() → ω
P_R_α:
P_R_β:                      jmp         patdef_R_omega
;  γ/ω ---------------------------------------------------------------------------------------------------------------
patdef_R_gamma:
                            jmp         [P_R_ret_γ]
;  R ===================================================================================================================
patdef_R_omega:             jmp         [P_R_ret_ω]

; P_N_α (α entry)
P_N_α:                      jmp         seq_l8_alpha ; SEQ
P_N_β:                      jmp         seq_r8_beta

; UNIMPLEMENTED: LT() → ω
seq_l8_alpha:
seq_l8_beta:                jmp         patdef_N_omega

; UNIMPLEMENTED node kind 8 → ω
seq_r8_alpha:
seq_r8_beta:                jmp         seq_l8_beta
;  γ/ω ---------------------------------------------------------------------------------------------------------------
patdef_N_gamma:
                            jmp         [P_N_ret_γ]
;  N ===================================================================================================================
patdef_N_omega:             jmp         [P_N_ret_ω]

; P_T2_α (α entry)

; UNIMPLEMENTED: TIME() → ω
P_T2_α:
P_T2_β:                     jmp         patdef_T2_omega
;  γ/ω ---------------------------------------------------------------------------------------------------------------
patdef_T2_gamma:
                            jmp         [P_T2_ret_γ]
;  T2 ==================================================================================================================
patdef_T2_omega:            jmp         [P_T2_ret_ω]

section .text
L_END_3:  ; STUB → _SNO_END (dangling or computed goto)
                            GOTO_ALWAYS L_SNO_END
L_RETURN_4:  ; STUB → _SNO_END (dangling or computed goto)
                            GOTO_ALWAYS L_SNO_END
L_FRETURN_5:  ; STUB → _SNO_END (dangling or computed goto)
                            GOTO_ALWAYS L_SNO_END
;  STUB LABELS =========================================================================================================

section .data
S_TRIM               db 84, 82, 73, 77, 0  ; "TRIM"
S_STLIMIT            db 83, 84, 76, 73, 77, 73, 84, 0  ; "STLIMIT"
S_DEFINE             db 68, 69, 70, 73, 78, 69, 0  ; "DEFINE"
S_ROMAN_LP_N_RP_T    db 82, 79, 77, 65, 78, 40, 78, 41, 84, 0  ; "ROMAN(N)T"
S_ROMAN              db 82, 79, 77, 65, 78, 0  ; "ROMAN"
S_N                  db 78, 0  ; "N"
S_T                  db 84, 0  ; "T"
S_LEN                db 76, 69, 78, 0  ; "LEN"
S_RPOS               db 82, 80, 79, 83, 0  ; "RPOS"
S_0_CM_1I_CM_2II_CM_3III_CM_4IV_CM_5V_CM_6VI_CM_7VII_CM_8VIII_C db 48, 44, 49, 73, 44, 50, 73, 73, 44, 51, 73, 73, 73, 44, 52, 73, 86, 44, 53, 86, 44, 54, 86, 73, 44, 55, 86, 73, 73, 44, 56, 86, 73, 73, 73, 44, 57, 73, 88, 44, 0  ; "0,1I,2II,3III,4IV,5V,6VI,7VII,8VIII,9IX,"
S_BREAK              db 66, 82, 69, 65, 75, 0  ; "BREAK"
S_CM                 db 44, 0  ; ","
S_REPLACE            db 82, 69, 80, 76, 65, 67, 69, 0  ; "REPLACE"
S_XLCDM_ST_ST        db 88, 76, 67, 68, 77, 42, 42, 0  ; "XLCDM**"
S_IVXLCDM            db 73, 86, 88, 76, 67, 68, 77, 0  ; "IVXLCDM"
S_ROMAN_END          db 82, 79, 77, 65, 78, 95, 69, 78, 68, 0  ; "ROMAN_END"
S_T1                 db 84, 49, 0  ; "T1"
S_TIME               db 84, 73, 77, 69, 0  ; "TIME"
S_LOOP               db 76, 79, 79, 80, 0  ; "LOOP"
S_R                  db 82, 0  ; "R"
S_1776               db 49, 55, 55, 54, 0  ; "1776"
S_LT                 db 76, 84, 0  ; "LT"
S_T2                 db 84, 50, 0  ; "T2"
S_OUTPUT             db 79, 85, 84, 80, 85, 84, 0  ; "OUTPUT"
S_result_CL_SP       db 114, 101, 115, 117, 108, 116, 58, 32, 0  ; "result: "
S_ms_CL_SP           db 109, 115, 58, 32, 0  ; "ms: "
S_END                db 69, 78, 68, 0  ; "END"
S_add                db 97, 100, 100, 0  ; "add"
S_sub                db 115, 117, 98, 0  ; "sub"
