; generated by sno2c -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var
extern  stmt_at_capture
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  comm_stno
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
P_ROMAN_ret_γ           resq 1
P_ROMAN_ret_ω           resq 1
fn_ROMAN_save_N_t        resq 1
fn_ROMAN_save_N_p        resq 1
fn_ROMAN_arg_0_t         resq 1
fn_ROMAN_arg_0_p         resq 1
P_T1_ret_γ              resq 1
P_T1_ret_ω              resq 1
P_R_ret_γ               resq 1
P_R_ret_ω               resq 1
P_N_ret_γ               resq 1
P_N_ret_ω               resq 1
P_T2_ret_γ              resq 1
P_T2_ret_ω              resq 1
scan_start_3             resq 1
scan_start_4             resq 1
dol_entry_T              resq 1
len2_saved               resq 1
litvar4_saved            resq 1
brk6_saved               resq 1
ucall0_sv_0_t            resq 1
ucall0_sv_0_p            resq 1
ucall0_rsv_g             resq 1
ucall0_rsv_o             resq 1
ucall1_sv_0_t            resq 1
ucall1_sv_0_p            resq 1
ucall1_rsv_g             resq 1
ucall1_rsv_o             resq 1
cap_T_buf                resb 256
cap_T_len                resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 4
                            call        comm_stno
                            ASSIGN_INT  S_TRIM, 1, Ln_0
                            jmp         Ln_0

; ======================================================================================================================
Ln_0:                       mov         edi, 5
                            call        comm_stno
                            ASSIGN_INT  S_STLIMIT, 1000000000, Ln_1
                            jmp         Ln_1

; ======================================================================================================================
Ln_1:                       mov         edi, 6
                            call        comm_stno
Ln_2:                       GOTO_ALWAYS L_ROMAN_END_0

;  ROMAN ===============================================================================================================
L_ROMAN_1:                  mov         edi, 7
                            call        comm_stno
                            GET_VAR     S_N
                            SUBJ_FROM16
                            mov         qword [scan_start_3], 0
scan_retry_3:
                            mov         rax, [scan_start_3]
                            mov         [cursor], rax
                            jmp         P_3_α

P_3_α:                      jmp         seq_l0_alpha ; SEQ
P_3_β:                      jmp         seq_r0_beta
seq_l0_alpha:               RPOS_ALPHA  1, cursor, subject_len_val, seq_r0_alpha, P_3_ω ; RPOS(%ld)
seq_l0_beta:                RPOS_BETA   cursor, P_3_ω

seq_r0_alpha: ; DOL(T $  T)
                            DOL_SAVE    dol_entry_T, cursor, dol1_child_alpha ; DOL α — save entry cursor
seq_r0_beta:                jmp         dol1_child_beta ; DOL β
dol1_child_alpha:           LEN_ALPHA   1, len2_saved, cursor, subject_len_val, dol1_gamma, dol1_omega ; LEN(%ld)
dol1_child_beta:            LEN_BETA    len2_saved, cursor, dol1_omega ; LEN β
dol1_gamma:                 DOL_CAPTURE dol_entry_T, cursor, cap_T_buf, cap_T_len, subject_data, P_3_γ ; DOL γ — capture span
dol1_omega:                 jmp         seq_l0_beta ; DOL ω — child failed

P_3_γ:                      SET_CAPTURE S_T, cap_T_buf, cap_T_len
                            mov         qword [rbp-32], 1
                            mov         qword [rbp-24], 0
                            APPLY_REPL_SPLICE S_N, scan_start_3
                            jmp         Ln_3
P_3_ω:                      cmp         qword [rel kw_anchor], 0
                            jne         scan_fail_tramp_0
                            mov         rax, [scan_start_3]
                            inc         rax
                            cmp         rax, [subject_len_val]
                            jg          scan_fail_tramp_0
                            mov         [scan_start_3], rax
                            jmp         scan_retry_3
scan_fail_tramp_0:
                            jmp         fn_ROMAN_gamma     ; RETURN
                            jmp         fn_ROMAN_gamma     ; RETURN

; ======================================================================================================================
Ln_3:                       mov         edi, 8
                            call        comm_stno
                            LOAD_STR    S_0_CM_1I_CM_2II_CM_3III_CM_4IV_CM_5V_CM_6VI_CM_7VII_CM_8VIII_CM_9IX_CM
                            mov         [rbp-16], rax
                            mov         [rbp-8],  rdx
                            SUBJ_FROM16
                            mov         qword [scan_start_4], 0
scan_retry_4:
                            mov         rax, [scan_start_4]
                            mov         [cursor], rax
                            jmp         P_4_α

P_4_α:                      jmp         seq_l3_alpha ; SEQ
P_4_β:                      jmp         seq_r3_beta

; E_VART T → LIT_VAR (stmt_match_var)
seq_l3_alpha:               LIT_VAR_ALPHA S_T, litvar4_saved, cursor, seq_r3_alpha, P_4_ω
seq_l3_beta:                LIT_VAR_BETA litvar4_saved, cursor, P_4_ω

seq_r3_alpha: ; DOL(T $  T)
                            DOL_SAVE    dol_entry_T, cursor, dol5_child_alpha ; DOL α — save entry cursor
seq_r3_beta:                jmp         dol5_child_beta ; DOL β
dol5_child_alpha:           BREAK_ALPHA lit_str_1, 1, brk6_saved, cursor, subject_data, subject_len_val, dol5_gamma, dol5_omega ; BREAK α
dol5_child_beta:            BREAK_BETA  brk6_saved, cursor, dol5_omega ; BREAK β
dol5_gamma:                 DOL_CAPTURE dol_entry_T, cursor, cap_T_buf, cap_T_len, subject_data, P_4_γ ; DOL γ — capture span
dol5_omega:                 jmp         seq_l3_beta ; DOL ω — child failed

P_4_γ:                      SET_CAPTURE S_T, cap_T_buf, cap_T_len
                            jmp         Ln_4
P_4_ω:                      cmp         qword [rel kw_anchor], 0
                            jne         scan_fail_tramp_1
                            mov         rax, [scan_start_4]
                            inc         rax
                            cmp         rax, [subject_len_val]
                            jg          scan_fail_tramp_1
                            mov         [scan_start_4], rax
                            jmp         scan_retry_4
scan_fail_tramp_1:
                            jmp         fn_ROMAN_omega     ; FRETURN
                            jmp         fn_ROMAN_omega     ; FRETURN

; ======================================================================================================================
Ln_4:                       mov         edi, 10
                            call        comm_stno
                            sub         rsp, 48
                            GET_VAR     S_N
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            GET_VAR     S_T
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            push        qword [P_ROMAN_ret_ω]
                            push        qword [P_ROMAN_ret_γ]
                            lea         rdi, [rel S_N]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            mov         rax, [rbp-32]
                            mov         rcx, [rbp-24]
                            mov         [fn_ROMAN_arg_0_t], rax
                            mov         [fn_ROMAN_arg_0_p], rcx
                            lea         rax, [rel ucall0_ret_g]
                            mov         [P_ROMAN_ret_γ], rax
                            lea         rax, [rel ucall0_ret_o]
                            mov         [P_ROMAN_ret_ω], rax
                            jmp         P_ROMAN_α
ucall0_ret_g:
                            pop         qword [P_ROMAN_ret_γ]
                            pop         qword [P_ROMAN_ret_ω]
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_T]
                            call        stmt_set
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_N]
                            call        stmt_set
                            GET_VAR     S_ROMAN
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            call        stmt_is_fail
                            test        eax, eax
                            jz          ucall0_has_val
                            LOAD_NULVCL32
                            jmp         ucall0_done
ucall0_has_val:
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            jmp         ucall0_done
ucall0_ret_o:
                            pop         qword [P_ROMAN_ret_γ]
                            pop         qword [P_ROMAN_ret_ω]
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_T]
                            call        stmt_set
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_N]
                            call        stmt_set
                            LOAD_FAILDESCR32
ucall0_done:
                            STORE_ARG32 0
                            LOAD_STR    S_IVXLCDM
                            STORE_ARG32 16
                            LOAD_STR    S_XLCDM_ST_ST
                            STORE_ARG32 32
                            APPLY_FN_N  S_REPLACE, 3
                            add         rsp, 48
                            STORE_RESULT
                            mov         [conc_tmp0_rax], rax
                            mov         [conc_tmp0_rdx], rdx
                            lea         rdi, [rel S_T]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            mov         rcx, rdx
                            mov         rdx, rax
                            mov         rdi, [conc_tmp0_rax]
                            mov         rsi, [conc_tmp0_rdx]
                            call        stmt_concat
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Ln_5
                            SET_VAR     S_ROMAN
                            jmp         fn_ROMAN_gamma     ; RETURN

Ln_5:
;  ROMAN_END ===========================================================================================================
L_ROMAN_END_0:              mov         edi, 12
                            call        comm_stno

; ======================================================================================================================
Ln_6:                       mov         edi, 13
                            call        comm_stno
                            APPLY_FN_0  S_TIME
                            STORE_RESULT
                            FAIL_BR     Ln_7
                            SET_VAR     S_T1
                            jmp         Ln_7

; ======================================================================================================================
Ln_7:                       mov         edi, 14
                            call        comm_stno
                            ASSIGN_INT  S_N, 0, Ln_8
                            jmp         Ln_8

Ln_8:
;  LOOP ================================================================================================================
L_LOOP_2:                   mov         edi, 15
                            call        comm_stno
                            GET_VAR     S_N
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            GET_VAR     S_T
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            push        qword [P_ROMAN_ret_ω]
                            push        qword [P_ROMAN_ret_γ]
                            LOAD_STR    S_1776
                            mov         rax, [rbp-32]
                            mov         rcx, [rbp-24]
                            mov         [fn_ROMAN_arg_0_t], rax
                            mov         [fn_ROMAN_arg_0_p], rcx
                            lea         rax, [rel ucall1_ret_g]
                            mov         [P_ROMAN_ret_γ], rax
                            lea         rax, [rel ucall1_ret_o]
                            mov         [P_ROMAN_ret_ω], rax
                            jmp         P_ROMAN_α
ucall1_ret_g:
                            pop         qword [P_ROMAN_ret_γ]
                            pop         qword [P_ROMAN_ret_ω]
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_T]
                            call        stmt_set
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_N]
                            call        stmt_set
                            GET_VAR     S_ROMAN
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            call        stmt_is_fail
                            test        eax, eax
                            jz          ucall1_has_val
                            LOAD_NULVCL32
                            jmp         ucall1_done
ucall1_has_val:
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            jmp         ucall1_done
ucall1_ret_o:
                            pop         qword [P_ROMAN_ret_γ]
                            pop         qword [P_ROMAN_ret_ω]
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_T]
                            call        stmt_set
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_N]
                            call        stmt_set
                            LOAD_FAILDESCR32
ucall1_done:
                            FAIL_BR     Ln_9
                            SET_VAR     S_R
                            jmp         Ln_9

; ======================================================================================================================
Ln_9:                       mov         edi, 16
                            call        comm_stno
                            CONC2_VI    S_LT, S_N, 100000
                            mov         [conc_tmp0_rax], rax
                            mov         [conc_tmp0_rdx], rdx
                            CONC2_VI    S_add, S_N, 1
                            mov         rcx, rdx
                            mov         rdx, rax
                            mov         rdi, [conc_tmp0_rax]
                            mov         rsi, [conc_tmp0_rdx]
                            call        stmt_concat
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Ln_10
                            SET_VAR     S_N
                            jmp         L_LOOP_2

; ======================================================================================================================
Ln_10:                      mov         edi, 17
                            call        comm_stno
                            APPLY_FN_0  S_TIME
                            STORE_RESULT
                            FAIL_BR     Ln_11
                            SET_VAR     S_T2
                            jmp         Ln_11

; ======================================================================================================================
Ln_11:                      mov         edi, 18
                            call        comm_stno
                            CAT2_SV     S_result_CL_SP, S_R
                            FAIL_BR     Ln_12
                            SET_OUTPUT
                            jmp         Ln_12

; ======================================================================================================================
Ln_12:                      mov         edi, 19
                            call        comm_stno
                            LOAD_STR    S_ms_CL_SP
                            mov         [conc_tmp0_rax], rax
                            mov         [conc_tmp0_rdx], rdx
                            CONC2_VV    S_sub, S_T2, S_T1
                            mov         rcx, rdx
                            mov         rdx, rax
                            mov         rdi, [conc_tmp0_rax]
                            mov         rsi, [conc_tmp0_rdx]
                            call        stmt_concat
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Ln_13
                            SET_OUTPUT
                            jmp         Ln_13
Ln_13:                      GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .data
lit_str_1            db 44

section .text

;  NAMED PATTERN BODIES ================================================================================================

; P_ROMAN_α — user function α entry (1 param)
;  ROMAN ===============================================================================================================
P_ROMAN_α:                  push        rbp
                            mov         rbp, rsp
                            sub         rsp, 56
                            lea         rdi, [rel S_N]
                            mov         rsi, [fn_ROMAN_arg_0_t]
                            mov         rdx, [fn_ROMAN_arg_0_p]
                            call        stmt_set
                            LOAD_NULVCL
                            lea         rdi, [rel S_ROMAN]
                            mov         rsi, [rbp-16]
                            mov         rdx, [rbp-8]
                            call        stmt_set
                            lea         rdi, [rel S_T]
                            mov         rsi, [rbp-16]
                            mov         rdx, [rbp-8]
                            call        stmt_set
                            jmp         L_ROMAN_1
;  γ/ω ---------------------------------------------------------------------------------------------------------------
fn_ROMAN_gamma:             add         rsp, 56
                            pop         rbp
                            jmp         [P_ROMAN_ret_γ]
fn_ROMAN_omega:             add         rsp, 56
                            pop         rbp
                            jmp         [P_ROMAN_ret_ω]

; P_T1_α (α entry)

; UNIMPLEMENTED: TIME() → ω
P_T1_α:
P_T1_β:                     jmp         patdef_T1_omega
;  γ/ω ---------------------------------------------------------------------------------------------------------------
patdef_T1_gamma:
;  T1 ==================================================================================================================
                            jmp         [P_T1_ret_γ]
patdef_T1_omega:            jmp         [P_T1_ret_ω]

; P_R_α (α entry)

; UNIMPLEMENTED: ROMAN() → ω
P_R_α:
P_R_β:                      jmp         patdef_R_omega
;  γ/ω ---------------------------------------------------------------------------------------------------------------
patdef_R_gamma:
;  R ===================================================================================================================
                            jmp         [P_R_ret_γ]
patdef_R_omega:             jmp         [P_R_ret_ω]

; P_N_α (α entry)
P_N_α:                      jmp         seq_l7_alpha ; SEQ
P_N_β:                      jmp         seq_r7_beta

; UNIMPLEMENTED: LT() → ω
seq_l7_alpha:
seq_l7_beta:                jmp         patdef_N_omega

; UNIMPLEMENTED node kind 8 → ω
seq_r7_alpha:
seq_r7_beta:                jmp         seq_l7_beta
;  γ/ω ---------------------------------------------------------------------------------------------------------------
patdef_N_gamma:
;  N ===================================================================================================================
                            jmp         [P_N_ret_γ]
patdef_N_omega:             jmp         [P_N_ret_ω]

; P_T2_α (α entry)

; UNIMPLEMENTED: TIME() → ω
P_T2_α:
P_T2_β:                     jmp         patdef_T2_omega
;  γ/ω ---------------------------------------------------------------------------------------------------------------
patdef_T2_gamma:
;  T2 ==================================================================================================================
                            jmp         [P_T2_ret_γ]
patdef_T2_omega:            jmp         [P_T2_ret_ω]

section .text
;  STUB LABELS =========================================================================================================

section .data
S_TRIM               db 84, 82, 73, 77, 0  ; "TRIM"
S_STLIMIT            db 83, 84, 76, 73, 77, 73, 84, 0  ; "STLIMIT"
S_DEFINE             db 68, 69, 70, 73, 78, 69, 0  ; "DEFINE"
S_ROMAN_LP_N_RP_T    db 82, 79, 77, 65, 78, 40, 78, 41, 84, 0  ; "ROMAN(N)T"
S_ROMAN              db 82, 79, 77, 65, 78, 0  ; "ROMAN"
S_N                  db 78, 0  ; "N"
S_T                  db 84, 0  ; "T"
S_LEN                db 76, 69, 78, 0  ; "LEN"
S_RPOS               db 82, 80, 79, 83, 0  ; "RPOS"
S_0_CM_1I_CM_2II_CM_3III_CM_4IV_CM_5V_CM_6VI_CM_7VII_CM_8VIII_CM_9IX_CM db 48, 44, 49, 73, 44, 50, 73, 73, 44, 51, 73, 73, 73, 44, 52, 73, 86, 44, 53, 86, 44, 54, 86, 73, 44, 55, 86, 73, 73, 44, 56, 86, 73, 73, 73, 44, 57, 73, 88, 44, 0  ; "0,1I,2II,3III,4IV,5V,6VI,7VII,8VIII,9IX,"
S_BREAK              db 66, 82, 69, 65, 75, 0  ; "BREAK"
S_CM                 db 44, 0  ; ","
S_REPLACE            db 82, 69, 80, 76, 65, 67, 69, 0  ; "REPLACE"
S_XLCDM_ST_ST        db 88, 76, 67, 68, 77, 42, 42, 0  ; "XLCDM**"
S_IVXLCDM            db 73, 86, 88, 76, 67, 68, 77, 0  ; "IVXLCDM"
S_ROMAN_END          db 82, 79, 77, 65, 78, 95, 69, 78, 68, 0  ; "ROMAN_END"
S_T1                 db 84, 49, 0  ; "T1"
S_TIME               db 84, 73, 77, 69, 0  ; "TIME"
S_LOOP               db 76, 79, 79, 80, 0  ; "LOOP"
S_R                  db 82, 0  ; "R"
S_1776               db 49, 55, 55, 54, 0  ; "1776"
S_LT                 db 76, 84, 0  ; "LT"
S_T2                 db 84, 50, 0  ; "T2"
S_OUTPUT             db 79, 85, 84, 80, 85, 84, 0  ; "OUTPUT"
S_result_CL_SP       db 114, 101, 115, 117, 108, 116, 58, 32, 0  ; "result: "
S_ms_CL_SP           db 109, 115, 58, 32, 0  ; "ms: "
S_END                db 69, 78, 68, 0  ; "END"
S_add                db 97, 100, 100, 0  ; "add"
S_sub                db 115, 117, 98, 0  ; "sub"
