; generated by sno2c -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o mock_engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var
extern  stmt_at_capture
extern  kw_anchor
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
P_WPAT_ret_γ            resq 1
P_WPAT_ret_ω            resq 1
scan_start_5             resq 1
brk2_saved               resq 1
span3_saved              resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
                            PROG_INIT


;  PROGRAM BODY ========================================================================================================

                            ASSIGN_INT  S_TRIM, 1, Ln_0
                            jmp         Ln_0

; ======================================================================================================================

; ======================================================================================================================
Ln_0:                       ASSIGN_STR  S_NUMERALS, S_0123456789, Ln_1
                            jmp         Ln_1

; ======================================================================================================================
Ln_1:                       CAT2_SV     S_XX_MI, S_NUMERALS
                            mov         [conc_tmp0_rax], rax
                            mov         [conc_tmp0_rdx], rdx
                            lea         rdi, [rel S_AM_UCASE]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            mov         rcx, rdx
                            mov         rdx, rax
                            mov         rdi, [conc_tmp0_rax]
                            mov         rsi, [conc_tmp0_rdx]
                            call        stmt_concat
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            mov         [conc_tmp0_rax], rax
                            mov         [conc_tmp0_rdx], rdx
                            lea         rdi, [rel S_AM_LCASE]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            mov         rcx, rdx
                            mov         rdx, rax
                            mov         rdi, [conc_tmp0_rax]
                            mov         rsi, [conc_tmp0_rdx]
                            call        stmt_concat
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Ln_2
                            SET_VAR     S_WORD
                            jmp         Ln_2

; ======================================================================================================================
Ln_2:                       CALL1_VAR   S_BREAK, S_WORD
                            mov         [conc_tmp0_rax], rax
                            mov         [conc_tmp0_rdx], rdx
                            CALL1_VAR   S_SPAN, S_WORD
                            mov         rcx, rdx
                            mov         rdx, rax
                            mov         rdi, [conc_tmp0_rax]
                            mov         rsi, [conc_tmp0_rdx]
                            call        stmt_concat
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Ln_3
                            SET_VAR     S_WPAT
                            jmp         Ln_3

Ln_3:
;  NEXTL ===============================================================================================================
L_NEXTL_0:                  lea         rdi, [rel S_INPUT]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Lf_4
                            SET_VAR     S_LINE
                            jmp         Ln_4
Lf_4:                       jmp         L_DONE_1

Ln_4:
;  NEXTW ===============================================================================================================
L_NEXTW_2:                  GET_VAR     S_LINE
                            SUBJ_FROM16

                            mov         qword [scan_start_5], 0
scan_retry_5:
                            mov         rax, [scan_start_5]
                            mov         [cursor], rax
                            jmp         P_5_α


P_5_α: ; REF(WPAT)
                            lea         rax, [rel nref0_gamma]
                            mov         [P_WPAT_ret_γ], rax
                            lea         rax, [rel nref0_omega]
                            mov         [P_WPAT_ret_ω], rax
                            jmp         P_WPAT_α
P_5_β:                      lea         rax, [rel nref0_gamma] ; REF(%s)
                            mov         [P_WPAT_ret_γ], rax
                            lea         rax, [rel nref0_omega]
                            mov         [P_WPAT_ret_ω], rax
                            jmp         P_WPAT_β

nref0_gamma:
                            jmp         P_5_γ
nref0_omega:                jmp         P_5_ω

P_5_γ:                      mov         qword [rbp-32], 1
                            mov         qword [rbp-24], 0
                            APPLY_REPL_SPLICE S_LINE, scan_start_5
                            jmp         Ln_5
P_5_ω:                      cmp         qword [rel kw_anchor], 0
                            jne         L_NEXTL_0
                            mov         rax, [scan_start_5]
                            inc         rax
                            cmp         rax, [subject_len_val]
                            jg          L_NEXTL_0
                            mov         [scan_start_5], rax
                            jmp         scan_retry_5
                            jmp         L_NEXTL_0

; ======================================================================================================================
Ln_5:                       CONC2_VI    S_add, S_N, 1
                            FAIL_BR     Ln_6
                            SET_VAR     S_N
                            jmp         L_NEXTW_2

Ln_6:
;  DONE ================================================================================================================
L_DONE_1:                   CAT2_VS     S_N, S_SP_words
                            FAIL_BR     Ln_7
                            SET_OUTPUT

                            jmp         Ln_7
Ln_7:                       GOTO_ALWAYS L_SNO_END

L_SNO_END:
                            PROG_END

;  END =================================================================================================================

section .text

;  NAMED PATTERN BODIES ================================================================================================

; P_WPAT_α (α entry)
P_WPAT_α:                   jmp         seq_l1_alpha ; SEQ
P_WPAT_β:                   jmp         seq_r1_beta
seq_l1_alpha:               BREAK_ALPHA_VAR S_WORD, brk2_saved, cursor, subject_data, subject_len_val, seq_r1_alpha, patdef_WPAT_omega ; BREAK(var) α
seq_l1_beta:                BREAK_BETA_VAR brk2_saved, cursor, patdef_WPAT_omega ; BREAK(var) β
seq_r1_alpha:               SPAN_ALPHA_VAR S_WORD, span3_saved, cursor, subject_data, subject_len_val, patdef_WPAT_gamma, seq_l1_beta ; SPAN(var) α
seq_r1_beta:                SPAN_BETA_VAR span3_saved, cursor, seq_l1_beta ; SPAN(var) β
;  γ/ω ---------------------------------------------------------------------------------------------------------------
patdef_WPAT_gamma:
                            jmp         [P_WPAT_ret_γ]
;  WPAT ================================================================================================================
patdef_WPAT_omega:          jmp         [P_WPAT_ret_ω]

section .text
L_END_3:  ; STUB → _SNO_END (dangling or computed goto)
                            GOTO_ALWAYS L_SNO_END
;  STUB LABELS =========================================================================================================

section .data
S_TRIM               db 84, 82, 73, 77, 0  ; "TRIM"
S_NUMERALS           db 78, 85, 77, 69, 82, 65, 76, 83, 0  ; "NUMERALS"
S_0123456789         db 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 0  ; "0123456789"
S_WORD               db 87, 79, 82, 68, 0  ; "WORD"
S_LCASE              db 76, 67, 65, 83, 69, 0  ; "LCASE"
S_UCASE              db 85, 67, 65, 83, 69, 0  ; "UCASE"
S_XX_MI              db 39, 45, 0  ; "'-"
S_WPAT               db 87, 80, 65, 84, 0  ; "WPAT"
S_SPAN               db 83, 80, 65, 78, 0  ; "SPAN"
S_BREAK              db 66, 82, 69, 65, 75, 0  ; "BREAK"
S_NEXTL              db 78, 69, 88, 84, 76, 0  ; "NEXTL"
S_LINE               db 76, 73, 78, 69, 0  ; "LINE"
S_INPUT              db 73, 78, 80, 85, 84, 0  ; "INPUT"
S_NEXTW              db 78, 69, 88, 84, 87, 0  ; "NEXTW"
S_N                  db 78, 0  ; "N"
S_DONE               db 68, 79, 78, 69, 0  ; "DONE"
S_OUTPUT             db 79, 85, 84, 80, 85, 84, 0  ; "OUTPUT"
S_SP_words           db 32, 119, 111, 114, 100, 115, 0  ; " words"
S_END                db 69, 78, 68, 0  ; "END"
S_AM_UCASE           db 38, 85, 67, 65, 83, 69, 0  ; "&UCASE"
S_AM_LCASE           db 38, 76, 67, 65, 83, 69, 0  ; "&LCASE"
S_add                db 97, 100, 100, 0  ; "add"
