/* Sprint 5: ARBNO empty — zero iterations succeeds
 * Pattern: POS(0) ARBNO(LIT("x")) RPOS(0)
 * Subject: ""
 * Expected: returns 0 (ARBNO matches empty string)
 */
/* Generated by snobol4x emit_c.py — DO NOT EDIT */
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "../../src/runtime/runtime.h"

/* === static storage === */
static int64_t cat_l3_cursors[64];
static int     cat_l3_depth;
static int64_t arbno_c5_saved_cursor;

int main(void) {
    const char *subject    = "";
    int64_t     subject_len = 0;
    int64_t     cursor      = 0;
    (void)cursor; (void)subject; (void)subject_len;

    goto root_alpha;

    
/* ===== pattern: root ===== */
    root_alpha: /* CAT — enter left */
        goto cat_l1_alpha;
    cat_l1_alpha:
        if (cursor != 0) goto root_beta;
        goto cat_r2_alpha;
    cat_l1_beta:
        goto root_beta;
    cat_r2_alpha: /* CAT — enter left */
        goto cat_l3_alpha;
    cat_l3_alpha:
        cat_l3_depth = -1;
        goto cat_r4_alpha;              /* ARBNO: zero matches → succeed */
    cat_l3_beta:
        cat_l3_depth++;
        if (cat_l3_depth >= 64) goto cat_r2_beta;  /* stack overflow */
        cat_l3_cursors[cat_l3_depth] = cursor;
        goto arbno_c5_alpha;
    arbno_c5_alpha:
        if (cursor + 1 > subject_len) goto cat_l3_child_fail;
        if (memcmp(subject + cursor, "x", 1) != 0) goto cat_l3_child_fail;
        arbno_c5_saved_cursor = cursor;
        cursor += 1;
        goto cat_l3_child_ok;
    arbno_c5_beta:
        cursor = arbno_c5_saved_cursor;
        goto cat_l3_child_fail;
    cat_l3_child_ok:
        goto cat_r4_alpha;              /* child matched → ARBNO succeeds again */
    cat_l3_child_fail:
        cursor = cat_l3_cursors[cat_l3_depth];
        cat_l3_depth--;
        goto cat_r2_beta;              /* child failed → ARBNO fails */
    cat_r4_alpha:
        if (cursor != subject_len - 0) goto cat_l3_beta;
        goto root_MATCH_SUCCESS;
    cat_r4_beta:
        goto cat_l3_beta;
    cat_r2_beta:
        goto cat_l1_beta;
    root_beta:
        goto root_MATCH_FAIL;
    root_MATCH_SUCCESS: return 0; /* matched */
    root_MATCH_FAIL:    return 1; /* failed  */
}
