/* Sprint 5: ARBNO + $ OUTPUT — immediate assign captures all intermediate lengths
 * Pattern: POS(0) ARBNO(LIT("x")) $ OUTPUT RPOS(0)
 * Subject: "xx"
 * Expected: prints empty line then "x" then "xx" ($ captures on each ARBNO success)
 *           returns 0
 */
/* Generated by snobol4x emit_c.py — DO NOT EDIT */
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "../../src/runtime/runtime.h"

/* === static storage === */
static str_t var_OUTPUT;
static int64_t cat_l3_start;
static int64_t assign_c5_cursors[64];
static int     assign_c5_depth;
static int64_t arbno_c6_saved_cursor;

int main(void) {
    const char *subject    = "xx";
    int64_t     subject_len = 2;
    int64_t     cursor      = 0;
    (void)cursor; (void)subject; (void)subject_len;

    goto root_alpha;

    
/* ===== pattern: root ===== */
    root_alpha: /* CAT — enter left */
        goto cat_l1_alpha;
    cat_l1_alpha:
        if (cursor != 0) goto root_beta;
        goto cat_r2_alpha;
    cat_l1_beta:
        goto root_beta;
    cat_r2_alpha: /* CAT — enter left */
        goto cat_l3_alpha;
    cat_l3_alpha:
        cat_l3_start = cursor;
        goto assign_c5_alpha;
    assign_c5_alpha:
        assign_c5_depth = -1;
        goto cat_l3_do_assign;              /* ARBNO: zero matches → succeed */
    assign_c5_beta:
        assign_c5_depth++;
        if (assign_c5_depth >= 64) goto cat_r2_beta;  /* stack overflow */
        assign_c5_cursors[assign_c5_depth] = cursor;
        goto arbno_c6_alpha;
    arbno_c6_alpha:
        if (cursor + 1 > subject_len) goto assign_c5_child_fail;
        if (memcmp(subject + cursor, "x", 1) != 0) goto assign_c5_child_fail;
        arbno_c6_saved_cursor = cursor;
        cursor += 1;
        goto assign_c5_child_ok;
    arbno_c6_beta:
        cursor = arbno_c6_saved_cursor;
        goto assign_c5_child_fail;
    assign_c5_child_ok:
        goto cat_l3_do_assign;              /* child matched → ARBNO succeeds again */
    assign_c5_child_fail:
        cursor = assign_c5_cursors[assign_c5_depth];
        assign_c5_depth--;
        goto cat_r2_beta;              /* child failed → ARBNO fails */
    cat_l3_do_assign:
        var_OUTPUT.ptr = subject + cat_l3_start;
        var_OUTPUT.len = cursor - cat_l3_start;
        sno_output(var_OUTPUT);
        goto cat_r4_alpha;
    cat_l3_beta:
        goto assign_c5_beta;
    cat_r4_alpha:
        if (cursor != subject_len - 0) goto cat_l3_beta;
        goto root_MATCH_SUCCESS;
    cat_r4_beta:
        goto cat_l3_beta;
    cat_r2_beta:
        goto cat_l1_beta;
    root_beta:
        goto root_MATCH_FAIL;
    root_MATCH_SUCCESS: return 0; /* matched */
    root_MATCH_FAIL:    return 1; /* failed  */
}
