#!/usr/bin/env python3
"""
build_expr_evaluator.py — Sprint 18

Builds a compiled expression evaluator by extending the Sprint 16
expression parser with value stack operations.

The grammar is identical to Expressions.py. The difference:
every pattern that produces a value pushes it onto the runtime
value stack (sno_vpush/sno_vpop). Operators pop their operands,
compute, push the result.

Mapping from Expressions.py evaluate() to value stack:

  parse_item() yields int(_1)     → sno_vpush(atoi(matched))
  parse_item() yields 'x'         → sno_vpush(10)
  parse_item() yields 'y'         → sno_vpush(20)
  parse_item() yields 'z'         → sno_vpush(30)
  parse_item() yields _2 (parens) → child already pushed TERM result

  parse_element() yields _1       → item value already on stack
  parse_element() yields ('+',_2) → a = sno_vpop(); sno_vpush(+a)
  parse_element() yields ('-',_2) → a = sno_vpop(); sno_vpush(-a)

  parse_factor() yields _1        → element value already on stack
  parse_factor() yields ('*',l,r) → r=pop(); l=pop(); push(l*r)
  parse_factor() yields ('/',l,r) → r=pop(); l=pop(); push(r==0?0:l//r)

  parse_term() yields _1          → factor value already on stack
  parse_term() yields ('+',l,r)   → r=pop(); l=pop(); push(l+r)
  parse_term() yields ('-',l,r)   → r=pop(); l=pop(); push(l-r)

The C is emitted by hand — not through emit_c.py — because the value
stack operations need to be woven into the match_ok paths of each
alternative, which the IR doesn't support yet.

Sprint 19 will add Compute nodes to the IR to make this general.
"""

import sys, os, subprocess, tempfile

HERE    = os.path.dirname(os.path.abspath(__file__))
ROOT    = os.path.join(HERE, '..', '..')
RUNTIME = os.path.abspath(os.path.join(ROOT, 'src', 'runtime'))


EVALUATOR_C = r"""
/* expr_evaluator.c — Generated by build_expr_evaluator.py (Sprint 18) */
/* DO NOT EDIT — regenerate from build_expr_evaluator.py               */

#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "RUNTIME_H"

/* === global match state === */
static const char *Sigma = 0;
static int64_t     Omega = 0;
static int64_t     Delta = 0;
static const str_t SNO_EMPTY = {0, 0};
static inline int64_t _slen(const char *s) { int64_t n=0; while(*s++) n++; return n; }
/* Floor division — matches Python // semantics (rounds toward -inf) */
static inline int64_t _floor_div(int64_t a, int64_t b) {
    if (b == 0) return 0;
    int64_t q = a / b;
    /* If signs differ and remainder non-zero, round down */
    if ((a ^ b) < 0 && q * b != a) q--;
    return q;
}

static inline int64_t _atoi_delta(int64_t start) {
    int64_t v = 0;
    for (int64_t i = start; i < Delta; i++) v = v*10 + (Sigma[i]-'0');
    return v;
}

/* === forward declarations === */
typedef struct _ITEM       ITEM_t;
typedef struct _ELEMENT    ELEMENT_t;
typedef struct _FACTOR     FACTOR_t;
typedef struct _TERM       TERM_t;
typedef struct _EXPRESSION EXPRESSION_t;

static str_t ITEM      (ITEM_t      **, int);
static str_t ELEMENT   (ELEMENT_t   **, int);
static str_t FACTOR    (FACTOR_t    **, int);
static str_t TERM      (TERM_t      **, int);
static str_t EXPRESSION(EXPRESSION_t**, int);

/* ===================================================================
   ITEM
   Alternatives (in order):
     1. SPAN('0123456789')  → push atoi(matched)
     2. 'x'                → push 10
     3. 'y'                → push 20
     4. 'z'                → push 30
     5. '(' TERM ')'       → TERM already pushed its value; parens transparent
   =================================================================== */
struct _ITEM {
    int     alt;          /* which alternative succeeded */
    int64_t span_start;   /* cursor before SPAN match    */
    int64_t span_save;    /* saved cursor for SPAN beta  */
    int64_t lit_save;     /* saved cursor for Lit beta   */
    TERM_t *term_z;       /* child frame for TERM        */
    int64_t paren_save;   /* saved cursor for '(' match  */
    int64_t rparen_save;  /* saved cursor for ')' match  */
    int     vdepth_save;  /* vstack depth on entry       */
};

static str_t ITEM(ITEM_t **zz, int entry) {
    ITEM_t *z = *zz;
    if (entry == 0) {
        z = (ITEM_t *)sno_enter((void **)zz, sizeof(ITEM_t));
        z->vdepth_save = sno_vdepth();
        goto ITEM_alpha;
    }
    if (!z) return SNO_EMPTY;
    goto ITEM_beta;

ITEM_alpha: z->alt = 0; goto ITEM_try1;

/* Alt 1: SPAN('0123456789') */
ITEM_try1:
    { int64_t st = Delta;
      while (Delta < Omega && Sigma[Delta] >= '0' && Sigma[Delta] <= '9') Delta++;
      if (Delta == st) goto ITEM_try2;
      z->span_start = st; z->span_save = st; z->alt = 1;
      sno_vpush(_atoi_delta(st));
      goto ITEM_ok; }
ITEM_span_beta:
    /* SPAN beta: try one shorter */
    if (Delta <= z->span_save + 1) { Delta = z->span_save; goto ITEM_try2; }
    Delta--;
    sno_vpush(_atoi_delta(z->span_start));
    goto ITEM_ok;

/* Alt 2: 'x' → push 10 */
ITEM_try2:
    if (Delta + 1 > Omega || Sigma[Delta] != 'x') goto ITEM_try3;
    z->lit_save = Delta; Delta++; z->alt = 2;
    sno_vpush(10);
    goto ITEM_ok;
ITEM_lit2_beta: Delta = z->lit_save; goto ITEM_try3;

/* Alt 3: 'y' → push 20 */
ITEM_try3:
    if (Delta + 1 > Omega || Sigma[Delta] != 'y') goto ITEM_try4;
    z->lit_save = Delta; Delta++; z->alt = 3;
    sno_vpush(20);
    goto ITEM_ok;
ITEM_lit3_beta: Delta = z->lit_save; goto ITEM_try4;

/* Alt 4: 'z' → push 30 */
ITEM_try4:
    if (Delta + 1 > Omega || Sigma[Delta] != 'z') goto ITEM_try5;
    z->lit_save = Delta; Delta++; z->alt = 4;
    sno_vpush(30);
    goto ITEM_ok;
ITEM_lit4_beta: Delta = z->lit_save; goto ITEM_try5;

/* Alt 5: '(' TERM ')' — TERM pushes its value; parens are transparent */
ITEM_try5:
    if (Delta + 1 > Omega || Sigma[Delta] != '(') goto ITEM_fail;
    z->paren_save = Delta; Delta++;
    z->term_z = 0;
    { str_t r = TERM(&z->term_z, 0);
      if (r.ptr == 0) { Delta = z->paren_save; goto ITEM_fail; }
      goto ITEM_after_term; }
ITEM_term_beta:
    { str_t r = TERM(&z->term_z, 1);
      if (r.ptr == 0) { Delta = z->paren_save; goto ITEM_fail; }
      goto ITEM_after_term; }
ITEM_after_term:
    if (Delta + 1 > Omega || Sigma[Delta] != ')') {
        /* backtrack through TERM */
        goto ITEM_term_beta; }
    z->rparen_save = Delta; Delta++; z->alt = 5;
    goto ITEM_ok;
ITEM_rparen_beta:
    Delta = z->rparen_save;
    goto ITEM_term_beta;

ITEM_ok: return (str_t){ Sigma, Delta };

ITEM_beta:
    /* restore vstack to entry depth before retrying */
    while (sno_vdepth() > z->vdepth_save) sno_vpop();
    if (z->alt == 1) goto ITEM_span_beta;
    if (z->alt == 2) goto ITEM_lit2_beta;
    if (z->alt == 3) goto ITEM_lit3_beta;
    if (z->alt == 4) goto ITEM_lit4_beta;
    if (z->alt == 5) goto ITEM_rparen_beta;
    goto ITEM_fail;

ITEM_fail:
    while (sno_vdepth() > z->vdepth_save) sno_vpop();
    sno_exit((void **)zz); return SNO_EMPTY;
}

/* ===================================================================
   ELEMENT
   Alternatives:
     1. ITEM()             → value already on stack from ITEM
     2. '+' ELEMENT()      → a = pop(); push(+a)
     3. '-' ELEMENT()      → a = pop(); push(-a)
   =================================================================== */
struct _ELEMENT {
    int       alt;
    ITEM_t   *item_z;
    int64_t   plus_save;
    int64_t   minus_save;
    ELEMENT_t *elem_z;
    int        vdepth_save;
};

static str_t ELEMENT(ELEMENT_t **zz, int entry) {
    ELEMENT_t *z = *zz;
    if (entry == 0) {
        z = (ELEMENT_t *)sno_enter((void **)zz, sizeof(ELEMENT_t));
        z->vdepth_save = sno_vdepth();
        goto ELEMENT_alpha;
    }
    if (!z) return SNO_EMPTY;
    goto ELEMENT_beta;

ELEMENT_alpha: z->alt = 0; goto ELEMENT_try1;

/* Alt 1: ITEM */
ELEMENT_try1:
    z->item_z = 0;
    { str_t r = ITEM(&z->item_z, 0);
      if (r.ptr == 0) goto ELEMENT_try2;
      z->alt = 1; goto ELEMENT_ok; }
ELEMENT_item_beta:
    { str_t r = ITEM(&z->item_z, 1);
      if (r.ptr == 0) goto ELEMENT_try2;
      z->alt = 1; goto ELEMENT_ok; }

/* Alt 2: '+' ELEMENT */
ELEMENT_try2:
    if (Delta + 1 > Omega || Sigma[Delta] != '+') goto ELEMENT_try3;
    z->plus_save = Delta; Delta++;
    z->elem_z = 0;
    { str_t r = ELEMENT(&z->elem_z, 0);
      if (r.ptr == 0) { Delta = z->plus_save; goto ELEMENT_try3; }
      /* a = pop(); push(+a) — unary plus is identity */
      z->alt = 2; goto ELEMENT_ok; }
ELEMENT_plus_elem_beta:
    { str_t r = ELEMENT(&z->elem_z, 1);
      if (r.ptr == 0) { Delta = z->plus_save; goto ELEMENT_try3; }
      z->alt = 2; goto ELEMENT_ok; }

/* Alt 3: '-' ELEMENT */
ELEMENT_try3:
    if (Delta + 1 > Omega || Sigma[Delta] != '-') goto ELEMENT_fail;
    z->minus_save = Delta; Delta++;
    z->elem_z = 0;
    { str_t r = ELEMENT(&z->elem_z, 0);
      if (r.ptr == 0) { Delta = z->minus_save; goto ELEMENT_fail; }
      { int64_t a = sno_vpop(); sno_vpush(-a); }
      z->alt = 3; goto ELEMENT_ok; }
ELEMENT_minus_elem_beta:
    { str_t r = ELEMENT(&z->elem_z, 1);
      if (r.ptr == 0) { Delta = z->minus_save; goto ELEMENT_fail; }
      { int64_t a = sno_vpop(); sno_vpush(-a); }
      z->alt = 3; goto ELEMENT_ok; }

ELEMENT_ok: return (str_t){ Sigma, Delta };

ELEMENT_beta:
    while (sno_vdepth() > z->vdepth_save) sno_vpop();
    if (z->alt == 1) goto ELEMENT_item_beta;
    if (z->alt == 2) goto ELEMENT_plus_elem_beta;
    if (z->alt == 3) goto ELEMENT_minus_elem_beta;
    goto ELEMENT_fail;

ELEMENT_fail:
    while (sno_vdepth() > z->vdepth_save) sno_vpop();
    sno_exit((void **)zz); return SNO_EMPTY;
}

/* ===================================================================
   FACTOR
   Alternatives:
     1. ELEMENT()                    → value on stack
     2. ELEMENT() '*' FACTOR()       → r=pop(); l=pop(); push(l*r)
     3. ELEMENT() '/' FACTOR()       → r=pop(); l=pop(); push(r==0?0:l/r)
   =================================================================== */
struct _FACTOR {
    int       alt;
    ELEMENT_t *elem_z;
    int64_t   op_save;
    FACTOR_t  *factor_z;
    int        vdepth_save;
    int64_t    saved_left;   /* left operand value for beta recovery */
};

static str_t FACTOR(FACTOR_t **zz, int entry) {
    FACTOR_t *z = *zz;
    if (entry == 0) {
        z = (FACTOR_t *)sno_enter((void **)zz, sizeof(FACTOR_t));
        z->vdepth_save = sno_vdepth();
        goto FACTOR_alpha;
    }
    if (!z) return SNO_EMPTY;
    goto FACTOR_beta;

FACTOR_alpha: z->alt = 0; goto FACTOR_try1;

/* Alt 1: ELEMENT */
FACTOR_try1:
    z->elem_z = 0;
    { str_t r = ELEMENT(&z->elem_z, 0);
      if (r.ptr == 0) goto FACTOR_try2;
      z->alt = 1; goto FACTOR_ok; }
FACTOR_elem1_beta:
    { str_t r = ELEMENT(&z->elem_z, 1);
      if (r.ptr == 0) goto FACTOR_try2;
      z->alt = 1; goto FACTOR_ok; }

/* Alt 2: ELEMENT '*' FACTOR */
FACTOR_try2:
    z->elem_z = 0;
    { str_t r = ELEMENT(&z->elem_z, 0);
      if (r.ptr == 0) goto FACTOR_try3;
      goto FACTOR_try2_op; }
FACTOR_elem2_beta:
    { str_t r = ELEMENT(&z->elem_z, 1);
      if (r.ptr == 0) goto FACTOR_try3;
      goto FACTOR_try2_op; }
FACTOR_try2_op:
    if (Delta + 1 > Omega || Sigma[Delta] != '*') {
        while (sno_vdepth() > z->vdepth_save) sno_vpop();
        goto FACTOR_elem2_beta; }
    z->saved_left = sno_vpeek();  /* save left before advancing */
    z->op_save = Delta; Delta++;
    z->factor_z = 0;
    { str_t r = FACTOR(&z->factor_z, 0);
      if (r.ptr == 0) { Delta = z->op_save;
          while (sno_vdepth() > z->vdepth_save) sno_vpop();
          goto FACTOR_elem2_beta; }
      { int64_t r2 = sno_vpop(), l = sno_vpop(); sno_vpush(l * r2); }
      z->alt = 2; goto FACTOR_ok; }
FACTOR_factor2_beta:
    { while (sno_vdepth() > z->vdepth_save) sno_vpop();
      sno_vpush(z->saved_left);   /* restore left operand */
      str_t r = FACTOR(&z->factor_z, 1);
      if (r.ptr == 0) { Delta = z->op_save;
          while (sno_vdepth() > z->vdepth_save) sno_vpop();
          goto FACTOR_elem2_beta; }
      { int64_t r2 = sno_vpop(), l = sno_vpop(); sno_vpush(l * r2); }
      z->alt = 2; goto FACTOR_ok; }

/* Alt 3: ELEMENT '/' FACTOR */
FACTOR_try3:
    z->elem_z = 0;
    { str_t r = ELEMENT(&z->elem_z, 0);
      if (r.ptr == 0) goto FACTOR_fail;
      goto FACTOR_try3_op; }
FACTOR_elem3_beta:
    { str_t r = ELEMENT(&z->elem_z, 1);
      if (r.ptr == 0) goto FACTOR_fail;
      goto FACTOR_try3_op; }
FACTOR_try3_op:
    if (Delta + 1 > Omega || Sigma[Delta] != '/') {
        while (sno_vdepth() > z->vdepth_save) sno_vpop();
        goto FACTOR_elem3_beta; }
    z->saved_left = sno_vpeek();
    z->op_save = Delta; Delta++;
    z->factor_z = 0;
    { str_t r = FACTOR(&z->factor_z, 0);
      if (r.ptr == 0) { Delta = z->op_save;
          while (sno_vdepth() > z->vdepth_save) sno_vpop();
          goto FACTOR_elem3_beta; }
      { int64_t r2 = sno_vpop(), l = sno_vpop();
        sno_vpush(_floor_div(l, r2)); }
      z->alt = 3; goto FACTOR_ok; }
FACTOR_factor3_beta:
    { while (sno_vdepth() > z->vdepth_save) sno_vpop();
      sno_vpush(z->saved_left);
      str_t r = FACTOR(&z->factor_z, 1);
      if (r.ptr == 0) { Delta = z->op_save;
          while (sno_vdepth() > z->vdepth_save) sno_vpop();
          goto FACTOR_elem3_beta; }
      { int64_t r2 = sno_vpop(), l = sno_vpop();
        sno_vpush(_floor_div(l, r2)); }
      z->alt = 3; goto FACTOR_ok; }

FACTOR_ok: return (str_t){ Sigma, Delta };

FACTOR_beta:
    while (sno_vdepth() > z->vdepth_save) sno_vpop();
    if (z->alt == 1) goto FACTOR_elem1_beta;
    if (z->alt == 2) goto FACTOR_factor2_beta;
    if (z->alt == 3) goto FACTOR_factor3_beta;
    goto FACTOR_fail;

FACTOR_fail:
    while (sno_vdepth() > z->vdepth_save) sno_vpop();
    sno_exit((void **)zz); return SNO_EMPTY;
}

/* ===================================================================
   TERM
   Alternatives:
     1. FACTOR()                    → value on stack
     2. FACTOR() '+' TERM()         → r=pop(); l=pop(); push(l+r)
     3. FACTOR() '-' TERM()         → r=pop(); l=pop(); push(l-r)
   =================================================================== */
struct _TERM {
    int      alt;
    FACTOR_t *factor_z;
    int64_t  op_save;
    TERM_t   *term_z;
    int       vdepth_save;
    int64_t   saved_left;   /* left operand value for beta recovery */
};

static str_t TERM(TERM_t **zz, int entry) {
    TERM_t *z = *zz;
    if (entry == 0) {
        z = (TERM_t *)sno_enter((void **)zz, sizeof(TERM_t));
        z->vdepth_save = sno_vdepth();
        goto TERM_alpha;
    }
    if (!z) return SNO_EMPTY;
    goto TERM_beta;

TERM_alpha: z->alt = 0; goto TERM_try1;

/* Alt 1: FACTOR */
TERM_try1:
    z->factor_z = 0;
    { str_t r = FACTOR(&z->factor_z, 0);
      if (r.ptr == 0) goto TERM_try2;
      z->alt = 1; goto TERM_ok; }
TERM_factor1_beta:
    { str_t r = FACTOR(&z->factor_z, 1);
      if (r.ptr == 0) goto TERM_try2;
      z->alt = 1; goto TERM_ok; }

/* Alt 2: FACTOR '+' TERM */
TERM_try2:
    z->factor_z = 0;
    { str_t r = FACTOR(&z->factor_z, 0);
      if (r.ptr == 0) goto TERM_try3;
      goto TERM_try2_op; }
TERM_factor2_beta:
    { str_t r = FACTOR(&z->factor_z, 1);
      if (r.ptr == 0) goto TERM_try3;
      goto TERM_try2_op; }
TERM_try2_op:
    if (Delta + 1 > Omega || Sigma[Delta] != '+') {
        while (sno_vdepth() > z->vdepth_save) sno_vpop();
        goto TERM_factor2_beta; }
    z->saved_left = sno_vpeek();
    z->op_save = Delta; Delta++;
    z->term_z = 0;
    { str_t r = TERM(&z->term_z, 0);
      if (r.ptr == 0) { Delta = z->op_save;
          while (sno_vdepth() > z->vdepth_save) sno_vpop();
          goto TERM_factor2_beta; }
      { int64_t r2 = sno_vpop(), l = sno_vpop(); sno_vpush(l + r2); }
      z->alt = 2; goto TERM_ok; }
TERM_term2_beta:
    { while (sno_vdepth() > z->vdepth_save) sno_vpop();
      sno_vpush(z->saved_left);
      str_t r = TERM(&z->term_z, 1);
      if (r.ptr == 0) { Delta = z->op_save;
          while (sno_vdepth() > z->vdepth_save) sno_vpop();
          goto TERM_factor2_beta; }
      { int64_t r2 = sno_vpop(), l = sno_vpop(); sno_vpush(l + r2); }
      z->alt = 2; goto TERM_ok; }

/* Alt 3: FACTOR '-' TERM */
TERM_try3:
    z->factor_z = 0;
    { str_t r = FACTOR(&z->factor_z, 0);
      if (r.ptr == 0) goto TERM_fail;
      goto TERM_try3_op; }
TERM_factor3_beta:
    { str_t r = FACTOR(&z->factor_z, 1);
      if (r.ptr == 0) goto TERM_fail;
      goto TERM_try3_op; }
TERM_try3_op:
    if (Delta + 1 > Omega || Sigma[Delta] != '-') {
        while (sno_vdepth() > z->vdepth_save) sno_vpop();
        goto TERM_factor3_beta; }
    z->saved_left = sno_vpeek();
    z->op_save = Delta; Delta++;
    z->term_z = 0;
    { str_t r = TERM(&z->term_z, 0);
      if (r.ptr == 0) { Delta = z->op_save;
          while (sno_vdepth() > z->vdepth_save) sno_vpop();
          goto TERM_factor3_beta; }
      { int64_t r2 = sno_vpop(), l = sno_vpop(); sno_vpush(l - r2); }
      z->alt = 3; goto TERM_ok; }
TERM_term3_beta:
    { while (sno_vdepth() > z->vdepth_save) sno_vpop();
      sno_vpush(z->saved_left);
      str_t r = TERM(&z->term_z, 1);
      if (r.ptr == 0) { Delta = z->op_save;
          while (sno_vdepth() > z->vdepth_save) sno_vpop();
          goto TERM_factor3_beta; }
      { int64_t r2 = sno_vpop(), l = sno_vpop(); sno_vpush(l - r2); }
      z->alt = 3; goto TERM_ok; }

TERM_ok: return (str_t){ Sigma, Delta };

TERM_beta:
    while (sno_vdepth() > z->vdepth_save) sno_vpop();
    if (z->alt == 1) goto TERM_factor1_beta;
    if (z->alt == 2) goto TERM_term2_beta;
    if (z->alt == 3) goto TERM_term3_beta;
    goto TERM_fail;

TERM_fail:
    while (sno_vdepth() > z->vdepth_save) sno_vpop();
    sno_exit((void **)zz); return SNO_EMPTY;
}

/* ===================================================================
   EXPRESSION = POS(0) TERM RPOS(0)
   After success: value is on top of the value stack.
   =================================================================== */
struct _EXPRESSION {
    int    entered;
    TERM_t *term_z;
};

static str_t EXPRESSION(EXPRESSION_t **zz, int entry) {
    EXPRESSION_t *z = *zz;
    if (entry == 0) {
        z = (EXPRESSION_t *)sno_enter((void **)zz, sizeof(EXPRESSION_t));
        goto EXPRESSION_alpha;
    }
    if (!z) return SNO_EMPTY;
    goto EXPRESSION_beta;

EXPRESSION_alpha:
    if (Delta != 0) goto EXPRESSION_fail;
    z->entered = 0;
    z->term_z  = 0;
    { str_t r = TERM(&z->term_z, 0);
      if (r.ptr == 0) goto EXPRESSION_fail;
      goto EXPRESSION_check_end; }
EXPRESSION_term_beta:
    { str_t r = TERM(&z->term_z, 1);
      if (r.ptr == 0) goto EXPRESSION_fail;
      goto EXPRESSION_check_end; }
EXPRESSION_check_end:
    if (Delta != Omega) { goto EXPRESSION_term_beta; }
    z->entered = 1;
    return (str_t){ Sigma, Delta };

EXPRESSION_beta:
    if (z->entered) goto EXPRESSION_term_beta;
    goto EXPRESSION_fail;

EXPRESSION_fail:
    sno_exit((void **)zz); return SNO_EMPTY;
}

/* ===================================================================
   main — accept expression on argv[1], print evaluated result
   =================================================================== */
int main(int argc, char **argv) {
    Sigma = (argc > 1) ? argv[1] : "";
    Omega = _slen(Sigma);
    Delta = 0;
    sno_arena_reset();
    sno_vreset();

    EXPRESSION_t *frame = 0;
    str_t r = EXPRESSION(&frame, 0);

    if (r.ptr == 0 || Delta != Omega) {
        fprintf(stderr, "Parse error\n");
        return 1;
    }

    if (sno_vdepth() != 1) {
        fprintf(stderr, "Value stack depth %d (expected 1)\n", sno_vdepth());
        return 1;
    }

    printf("%lld\n", (long long)sno_vpop());
    return 0;
}
"""


def build_evaluator(out_path=None):
    src = EVALUATOR_C.replace('RUNTIME_H', f'{RUNTIME}/runtime.h')

    with tempfile.NamedTemporaryFile(suffix='.c', mode='w', delete=False) as f:
        f.write(src)
        c_path = f.name

    if out_path is None:
        out_path = c_path.replace('.c', '')

    result = subprocess.run(
        ['cc', '-O2', '-o', out_path, c_path,
         os.path.join(RUNTIME, 'runtime.c'), f'-I{RUNTIME}'],
        capture_output=True, text=True
    )
    os.unlink(c_path)

    if result.returncode != 0:
        print("Compile error:", file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        return None

    return out_path


if __name__ == '__main__':
    print("Building expression evaluator...")
    with tempfile.NamedTemporaryFile(suffix='', delete=False) as f:
        bin_path = f.name

    path = build_evaluator(out_path=bin_path)
    if path:
        print(f"Binary: {path}")
        for expr, expected in [
            ('x',           10),
            ('y',           20),
            ('z',           30),
            ('42',          42),
            ('x+y',         30),
            ('x*y',        200),
            ('x+y*z',      610),   # x + (y*z) = 10 + 600
            ('(x+y)*z',    900),
            ('+x',          10),
            ('-y',         -20),
            ('x/y',          0),   # integer division
            ('z/x',          3),
        ]:
            r = subprocess.run([path, expr], capture_output=True, text=True)
            got = int(r.stdout.strip()) if r.returncode == 0 else None
            ok = (got == expected)
            print(f"  {'OK' if ok else 'FAIL'} {expr!r:20s} → {got!r:6}  (expected {expected})")
        import os
        os.unlink(path)
