/* Generated by snobol4x emit_c.py — DO NOT EDIT */
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "../../src/runtime/runtime.h"

/* === static storage === */

int main(void) {
    const char *subject    = "";
    int64_t     subject_len = 0;
    int64_t     cursor      = 0;
    (void)cursor; (void)subject; (void)subject_len;

    goto root_alpha;

    
/* ===== pattern: root ===== */
    root_alpha: /* CAT — enter left */
        goto cat_l1_alpha;
    cat_l1_alpha:
        if (cursor != 0) goto root_beta;
        goto cat_r2_alpha;
    cat_l1_beta:
        goto root_beta;
    cat_r2_alpha:
        if (cursor != subject_len - 0) goto cat_l1_beta;
        goto root_MATCH_SUCCESS;
    cat_r2_beta:
        goto cat_l1_beta;
    root_beta:
        goto root_MATCH_FAIL;
    root_MATCH_SUCCESS: return 0; /* matched */
    root_MATCH_FAIL:    return 1; /* failed  */
}
