#!/usr/bin/env bash
# Run rung-12 crosscheck tests: pipe each .input through beauty_full_bin,
# diff against .ref generated by oracle snobol4.
# Usage: bash test/crosscheck/run_beauty.sh
# Must be run from snobol4x root.

set -euo pipefail

BINARY=./beauty_full_bin
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TINY="$(cd "$SCRIPT_DIR/../.." && pwd)"
CORPUS="${CORPUS:-$TINY/../corpus/crosscheck/beauty}"

if [[ ! -x "$BINARY" ]]; then
    echo "ERROR: $BINARY not found or not executable. Build it first." >&2
    exit 1
fi

if [[ ! -d "$CORPUS" ]]; then
    echo "ERROR: corpus dir $CORPUS not found." >&2
    exit 1
fi

PASS=0; FAIL=0; SKIP=0
FAILED_LIST=""

for INPUT in "$CORPUS"/*.input; do
    NAME=$(basename "$INPUT" .input)
    REF="$CORPUS/$NAME.ref"

    if [[ ! -f "$REF" ]]; then
        echo "SKIP  $NAME  (no .ref)"
        SKIP=$((SKIP+1))
        continue
    fi

    ACTUAL=$(tmp=$(mktemp); "$BINARY" < "$INPUT" > "$tmp" 2>/dev/null; cat "$tmp"; rm -f "$tmp")
    EXPECTED=$(cat "$REF")

    if [[ "$ACTUAL" == "$EXPECTED" ]]; then
        echo "PASS  $NAME"
        PASS=$((PASS+1))
    else
        echo "FAIL  $NAME"
        diff <(echo "$EXPECTED") <(echo "$ACTUAL") | head -10
        FAIL=$((FAIL+1))
        FAILED_LIST="$FAILED_LIST $NAME"
    fi
done

echo ""
echo "============================================"
echo "Results: $PASS passed, $FAIL failed, $SKIP skipped"
if [[ $FAIL -eq 0 ]]; then
    echo "ALL PASS"
else
    echo "FAILED:$FAILED_LIST"
    exit 1
fi
