/*
 * emit_wasm.c — WebAssembly text-format emitter for scrip-cc (scaffold)
 *
 * Skeleton only — Phase 2 scaffold (M-G2-SCAFFOLD-WASM).
 * No IR node handling yet. Entry point compiles and links clean.
 *
 * Naming law: W(fmt,...) for output, WI(op,arg) for instructions,
 * WL(label) for labels — mirrors E()/J()/N() in x86/JVM/.NET emitters.
 *
 * Produced by: Claude Sonnet 4.6 (G-7 session, 2026-03-28)
 * Milestone: M-G2-SCAFFOLD-WASM
 */

#include "scrip_cc.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ── Output macros ────────────────────────────────────────────────────── */
#define W(fmt, ...)   fprintf(wasm_out, fmt, ##__VA_ARGS__)
#define WI(op, arg)   fprintf(wasm_out, "    %s %s\n", (op), (arg))
#define WL(lbl)       fprintf(wasm_out, "  %s:\n", (lbl))

static FILE *wasm_out = NULL;

/* ── Public entry point ───────────────────────────────────────────────── */

/*
 * emit_wasm — compile a Program to WebAssembly text format (.wat).
 *
 * Currently a stub: emits a valid empty module as a placeholder.
 * IR node handling will be wired in during Phase 5 (frontend unification)
 * and Phase 6 (WASM-specific milestones M-G6-*).
 */
void emit_wasm(Program *prog, FILE *out, const char *filename) {
    (void)prog;      /* unused until IR wiring */
    (void)filename;  /* unused until IR wiring */

    wasm_out = out;

    W(";; Generated by scrip-cc WASM emitter (scaffold — M-G2-SCAFFOLD-WASM)\n");
    W(";; IR node handling not yet implemented.\n");
    W("(module\n");
    W("  ;; placeholder\n");
    W(")\n");
}
