/*
 * pl_emit.c — Prolog IR -> C code emitter (Byrd box four-port model)
 *
 * Implements the Proebsting technique from:
 *   "Simple Translation of Goal-Directed Evaluation" (Todd A. Proebsting, 1996)
 *
 * Each IR node kind gets four labeled code chunks: α β γ ω
 *   α  (α / start)  — initial entry, try-head
 *   β  (β  / resume) — re-entry after backtrack, try next clause
 *   γ  (γ / succeed)— departure on success
 *   ω  (ω / fail)   — departure on failure / all clauses exhausted
 *
 * Byrd Box wiring for clause selection (per FRONTEND-PROLOG.md):
 *
 *   P_FOO_α:                             ← entry (E_TRAIL_MARK, try clause 1 head)
 *       if (!unify(arg, head1)) goto P_FOO_β;
 *       <body clause 1>
 *       goto ret_γ;
 *
 *   P_FOO_β:                             ← backtrack (E_TRAIL_UNWIND, try clause 2)
 *       trail_unwind(&_trail, _mark);
 *       if (!unify(arg, head2)) goto P_FOO_ω;
 *       <body clause 2>
 *       goto ret_γ;
 *
 *   P_FOO_ω:                             ← all exhausted
 *       trail_unwind(&_trail, _mark);
 *       goto ret_ω;
 *
 * Cut (E_CUT) seals β → ω.  Exactly FENCE semantics.
 *
 * Entry point: pl_emit(Program*, FILE*)
 *
 * Build notes:
 *   This file is included by the sno2c driver when -pl is active.
 *   It #includes emit_pretty.h from the C backend for the PLG/PL/PS/PG macros.
 *   Compile with:
 *     gcc -I src/frontend/snobol4 -I src/frontend/prolog \
 *         -I src/backend/c pl_emit.c prolog_atom.c -c
 */

#define EMIT_BYRD_PL_C
#include "sno2c.h"
#include "prolog_atom.h"
#include "prolog_runtime.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <ctype.h>

/* =========================================================================
 * Output helpers
 * ======================================================================= */

static FILE *pl_out;
static int   pl_uid_ctr = 0;
static int   pl_next_uid(void) { return ++pl_uid_ctr; }

static void PL_C(const char *fmt, ...) {
    va_list ap; va_start(ap, fmt); vfprintf(pl_out, fmt, ap); va_end(ap);
}

/* Emit a C string literal body with proper escaping */
static void emit_c_string(const char *s) {
    for (; *s; s++) {
        if      (*s == '"')                  PL_C("\\\"");
        else if (*s == '\\')                 PL_C("\\\\");
        else if (*s == '\n')                 PL_C("\\n");
        else if (*s == '\r')                 PL_C("\\r");
        else if (*s == '\t')                 PL_C("\\t");
        else if ((unsigned char)*s < 32)     PL_C("\\x%02x", (unsigned char)*s);
        else                                 PL_C("%c", *s);
    }
}


/* Use the same 3-column pretty-printer as the C backend */
#define PRETTY_OUT pl_out
#include "emit_pretty.h"

/* =========================================================================
 * Label buffer size
 * ======================================================================= */
#define LBUF 128

/* =========================================================================
 * C-safe identifier from an atom name
 * ======================================================================= */
static char *safe_name(const char *s) {
    static char buf[256];
    int j = 0;
    buf[j++] = 'p'; buf[j++] = '_';  /* prefix to avoid C keyword clashes */
    for (int i = 0; s[i] && j < 250; i++) {
        unsigned char c = (unsigned char)s[i];
        buf[j++] = (isalnum(c) || c == '_') ? (char)c : '_';
    }
    buf[j] = '\0';
    return buf;
}

/* =========================================================================
 * Forward declarations
 * ======================================================================= */
static void emit_goal(EXPR_t *goal, int uid,
                      const char *γ, const char *ω);
static void emit_body(EXPR_t **goals, int ngoals, int base_uid,
                      const char *γ, const char *ω);
static void emit_choice(EXPR_t *choice);
static void emit_term_val(EXPR_t *e);   /* emit a Term* value expression */

/* =========================================================================
 * Runtime preamble — included once at top of emitted file
 * ======================================================================= */
static void emit_pl_preamble(void) {
    PL_C("/* ---- Prolog runtime (generated by pl_emit.c) ---- */\n");
    PL_C("#include <stdio.h>\n");
    PL_C("#include <stdlib.h>\n");
    PL_C("#include <string.h>\n");
    PL_C("#include \"term.h\"\n");
    PL_C("#include \"prolog_atom.h\"\n");
    PL_C("#include \"prolog_runtime.h\"\n");
    PL_C("#include \"prolog_builtin.h\"\n");
    PL_C("\n");
    PL_C("static Trail _trail;\n");
    PL_C("static int   _mark;\n\n");
}

/* =========================================================================
 * Emit a term as a C expression producing a Term*
 *
 * For the current compile-time evaluator we build terms fresh each call.
 * A future pass can hoist constants.
 * ======================================================================= */
static void emit_term_val(EXPR_t *e) {
    if (!e) { PL_C("term_new_atom(ATOM_NIL)"); return; }
    switch (e->kind) {
        case E_QLIT: {
            /* atom literal */
            const char *name = e->sval ? e->sval : "";
            /* Special-case well-known atoms */
            if (strcmp(name, "[]") == 0)  { PL_C("term_new_atom(ATOM_NIL)"); return; }
            if (strcmp(name, "true") == 0){ PL_C("term_new_atom(ATOM_TRUE)"); return; }
            if (strcmp(name, "fail") == 0){ PL_C("term_new_atom(ATOM_FAIL)"); return; }
            /* General atom: intern at runtime */
            PL_C("term_new_atom(prolog_atom_intern(\"");
            emit_c_string(name);
            PL_C("\"))");
            return;
        }
        case E_ILIT:
            PL_C("term_new_int(%ldL)", e->ival);
            return;
        case E_FLIT:
            PL_C("term_new_float(%g)", e->dval);
            return;
        case E_VART: {
            /* variable slot: reference into env frame array _env[] */
            long slot = e->ival;
            if (slot < 0) {
                PL_C("term_new_var(-1)");  /* anonymous wildcard — always unifies */
            } else {
                PL_C("_env[%ld]", slot);
            }
            return;
        }
        case E_FNC: {
            /* compound term: f(arg0, arg1, ...) */
            const char *fn = e->sval ? e->sval : "?";
            int arity = e->nchildren;
            if (arity == 0) {
                PL_C("term_new_atom(prolog_atom_intern(\""); emit_c_string(fn); PL_C("\"))");
            } else {
                /* Capture uid BEFORE emitting children — nested compounds
                 * call pl_next_uid() and would collide with pl_uid_ctr. */
                int cuid = pl_next_uid();
                PL_C("({\n");
                PL_C("    Term *_args%d[%d];\n", cuid, arity);
                for (int i = 0; i < arity; i++) {
                    PL_C("    _args%d[%d] = ", cuid, i);
                    emit_term_val(e->children[i]);
                    PL_C(";\n");
                }
                PL_C("    term_new_compound(prolog_atom_intern(\""); emit_c_string(fn); PL_C("\"), %d, _args%d);\n", arity, cuid);
                PL_C("})");
            }
            return;
        }
        case E_ADD: case E_SUB: case E_MPY: case E_DIV: {
            /* Arithmetic subexpression — only valid inside is/2 rhs.
             * Emitted as integer Term* nodes evaluated at runtime. */
            const char *op = (e->kind == E_ADD) ? "+" :
                             (e->kind == E_SUB) ? "-" :
                             (e->kind == E_MPY) ? "*" : "/";
            PL_C("term_new_int(");
            PL_C("(");
            emit_term_val(e->children[0]);
            PL_C(")->ival %s (", op);
            emit_term_val(e->children[1]);
            PL_C(")->ival)");
            return;
        }
        default:
            PL_C("term_new_atom(ATOM_NIL)");
            return;
    }
}

/* =========================================================================
 * emit_goal — emit code for one body goal
 *
 * Each goal gets a uid-stamped γ label (goal_N_γ) and shares the
 * caller's ω (backtrack to invoker on failure).
 *
 * Proebsting template: goal succeeds → fall to γ, fails → jump ω.
 * ======================================================================= */

/* Emit arithmetic evaluation: walk the rhs E_FNC("is") tree */
static void emit_arith_expr(EXPR_t *e) {
    if (!e) { PL_C("0"); return; }
    switch (e->kind) {
        case E_ILIT: PL_C("%ldL", e->ival); return;
        case E_FLIT: PL_C("%g",   e->dval); return;
        case E_VART: PL_C("(term_deref(_env[%ld])->ival)", e->ival); return;
        case E_ADD:
            PL_C("("); emit_arith_expr(e->children[0]);
            PL_C(" + "); emit_arith_expr(e->children[1]); PL_C(")"); return;
        case E_SUB:
            PL_C("("); emit_arith_expr(e->children[0]);
            PL_C(" - "); emit_arith_expr(e->children[1]); PL_C(")"); return;
        case E_MPY:
            PL_C("("); emit_arith_expr(e->children[0]);
            PL_C(" * "); emit_arith_expr(e->children[1]); PL_C(")"); return;
        case E_DIV:
            PL_C("("); emit_arith_expr(e->children[0]);
            PL_C(" / "); emit_arith_expr(e->children[1]); PL_C(")"); return;
        default: PL_C("0"); return;
    }
}

static void emit_goal(EXPR_t *goal, int uid,
                      const char *γ, const char *ω) {
    if (!goal) { PG(γ); return; }

    char lbl[LBUF];

    switch (goal->kind) {

        /* ----------------------------------------------------------------
         * E_UNIFY — Robinson unification with trail
         * Byrd: α: attempt unify; success→γ, failure→ω
         * ---------------------------------------------------------------- */
        case E_UNIFY: {
            snprintf(lbl, LBUF, "unify%d_α", uid);
            PLG(lbl, NULL);
            int mark_uid = pl_next_uid();
            PL_C("    int _um%d = trail_mark(&_trail);\n", mark_uid);
            PL_C("    if (!unify(");
            emit_term_val(goal->children[0]);
            PL_C(", ");
            emit_term_val(goal->children[1]);
            PL_C(", &_trail)) { trail_unwind(&_trail, _um%d); goto %s; }\n",
                 mark_uid, ω);
            PG(γ);
            return;
        }

        /* ----------------------------------------------------------------
         * E_CUT — seal β, force ω on backtrack (FENCE semantics)
         * In a body context: always succeeds (→γ), cuts enclosing choice.
         * The enclosing E_CHOICE emitter sets _cut_flag when it sees E_CUT.
         * ---------------------------------------------------------------- */
        case E_CUT: {
            snprintf(lbl, LBUF, "cut%d_α", uid);
            PLG(lbl, NULL);
            PS(NULL, "_cut = 1;");
            PG(γ);
            return;
        }

        /* ----------------------------------------------------------------
         * E_FNC — builtin or user-defined predicate call
         * ---------------------------------------------------------------- */
        case E_FNC: {
            const char *fn = goal->sval ? goal->sval : "true";
            int arity = goal->nchildren;

            /* --- builtins handled directly --- */

            /* true/0 */
            if (strcmp(fn, "true") == 0 && arity == 0) {
                PG(γ); return;
            }
            /* fail/0 — always fails */
            if (strcmp(fn, "fail") == 0 && arity == 0) {
                PG(ω); return;
            }
            /* halt/0 */
            if (strcmp(fn, "halt") == 0 && arity == 0) {
                PS(NULL, "exit(0);"); return;
            }
            /* halt/1 */
            if (strcmp(fn, "halt") == 0 && arity == 1) {
                PL_C("    exit((int)(");
                emit_term_val(goal->children[0]);
                PL_C(")->ival);\n");
                return;
            }
            /* nl/0 */
            if (strcmp(fn, "nl") == 0 && arity == 0) {
                PS(NULL, "putchar('\\n');");
                PG(γ); return;
            }
            /* write/1 */
            if (strcmp(fn, "write") == 0 && arity == 1) {
                PL_C("    pl_write(");
                emit_term_val(goal->children[0]);
                PL_C(");\n");
                PG(γ); return;
            }
            /* writeln/1 */
            if (strcmp(fn, "writeln") == 0 && arity == 1) {
                PL_C("    pl_write(");
                emit_term_val(goal->children[0]);
                PL_C("); putchar('\\n');\n");
                PG(γ); return;
            }
            /* is/2  — arithmetic evaluation */
            if (strcmp(fn, "is") == 0 && arity == 2) {
                snprintf(lbl, LBUF, "is%d_α", uid);
                PLG(lbl, NULL);
                int mark_uid2 = pl_next_uid();
                PL_C("    { int _im%d = trail_mark(&_trail);\n", mark_uid2);
                PL_C("      Term *_isval%d = term_new_int(", uid);
                emit_arith_expr(goal->children[1]);
                PL_C(");\n");
                PL_C("      if (!unify(");
                emit_term_val(goal->children[0]);
                PL_C(", _isval%d, &_trail)) { trail_unwind(&_trail, _im%d); goto %s; }\n",
                     uid, mark_uid2, ω);
                PL_C("    }\n");
                PG(γ); return;
            }
            /* Comparison operators via is-style: < > =< >= =:= =\= */
            {
                struct { const char *name; const char *cop; } cmps[] = {
                    { "<",   "<"  }, { ">",   ">"  },
                    { "=<",  "<=" }, { ">=",  ">=" },
                    { "=:=", "==" }, { "=\\=","!=" },
                    { NULL, NULL }
                };
                for (int ci = 0; cmps[ci].name; ci++) {
                    if (strcmp(fn, cmps[ci].name) == 0 && arity == 2) {
                        snprintf(lbl, LBUF, "cmp%d_α", uid);
                        PLG(lbl, NULL);
                        PL_C("    if (!(");
                        emit_arith_expr(goal->children[0]);
                        PL_C(" %s ", cmps[ci].cop);
                        emit_arith_expr(goal->children[1]);
                        PL_C(")) goto %s;\n", ω);
                        PG(γ); return;
                    }
                }
            }
            /* =/2 structural equality (re-routed from E_UNIFY path) */
            if (strcmp(fn, "=") == 0 && arity == 2) {
                snprintf(lbl, LBUF, "eq%d_α", uid);
                PLG(lbl, NULL);
                int mu = pl_next_uid();
                PL_C("    int _em%d = trail_mark(&_trail);\n", mu);
                PL_C("    if (!unify(");
                emit_term_val(goal->children[0]);
                PL_C(", ");
                emit_term_val(goal->children[1]);
                PL_C(", &_trail)) { trail_unwind(&_trail, _em%d); goto %s; }\n", mu, ω);
                PG(γ); return;
            }
            /* \=/2 — not unifiable */
            if (strcmp(fn, "\\=") == 0 && arity == 2) {
                snprintf(lbl, LBUF, "neq%d_α", uid);
                PLG(lbl, NULL);
                int mu = pl_next_uid();
                PL_C("    { int _nm%d = trail_mark(&_trail);\n", mu);
                PL_C("      int _nr%d = unify(", mu);
                emit_term_val(goal->children[0]);
                PL_C(", ");
                emit_term_val(goal->children[1]);
                PL_C(", &_trail);\n");
                PL_C("      trail_unwind(&_trail, _nm%d);\n", mu);
                PL_C("      if (_nr%d) goto %s; }\n", mu, ω);
                PG(γ); return;
            }
            /* var/1, nonvar/1, atom/1, integer/1, compound/1 type tests */
            {
                struct { const char *name; const char *test; } tests[] = {
                    { "var",      "TT_VAR"      },
                    { "nonvar",   "!TT_VAR"     },
                    { "atom",     "TT_ATOM"     },
                    { "integer",  "TT_INT"      },
                    { "float",    "TT_FLOAT"    },
                    { "compound", "TT_COMPOUND" },
                    { NULL, NULL }
                };
                for (int ti = 0; tests[ti].name; ti++) {
                    if (strcmp(fn, tests[ti].name) == 0 && arity == 1) {
                        snprintf(lbl, LBUF, "type%d_α", uid);
                        PLG(lbl, NULL);
                        PL_C("    { Term *_t%d = term_deref(", uid);
                        emit_term_val(goal->children[0]);
                        PL_C(");\n");
                        if (strncmp(tests[ti].test, "!", 1) == 0) {
                            PL_C("      if (_t%d && _t%d->tag == %s) goto %s; }\n",
                                 uid, uid, tests[ti].test + 1, ω);
                        } else {
                            PL_C("      if (!_t%d || _t%d->tag != %s) goto %s; }\n",
                                 uid, uid, tests[ti].test, ω);
                        }
                        PG(γ); return;
                    }
                }
            }

            /* ,/2 — conjunction: flatten tree and emit via emit_body so
             * user-calls inside get the Proebsting retry loop.
             * E2.fail → E1.resume wiring is in emit_body, not here. */
            if (strcmp(fn, ",") == 0 && arity == 2) {
                EXPR_t *flat[256]; int nflat = 0;
                EXPR_t *cur = goal;
                while (cur && cur->kind == E_FNC && cur->sval &&
                       strcmp(cur->sval, ",") == 0 && cur->nchildren == 2) {
                    if (nflat < 255) flat[nflat++] = cur->children[0];
                    cur = cur->children[1];
                }
                if (cur && nflat < 256) flat[nflat++] = cur;
                emit_body(flat, nflat, pl_next_uid(), γ, ω);
                return;
            }

            /* ;/2 — disjunction: A ; B
             * Proebsting if-stmt model: try A; on failure try B.
             * Also handles (Cond -> Then ; Else) three-way. */
            if (strcmp(fn, ";") == 0 && arity == 2) {
                EXPR_t *left  = goal->children[0];
                EXPR_t *right = goal->children[1];
                /* Check if left is ->/2 (if-then) */
                if (left && left->kind == E_FNC && left->sval &&
                    strcmp(left->sval, "->") == 0 && left->nchildren == 2) {
                    /* (Cond -> Then ; Else) */
                    char else_lbl[LBUF], done_lbl[LBUF];
                    snprintf(else_lbl, LBUF, "disj%d_else", uid);
                    snprintf(done_lbl, LBUF, "disj%d_done", uid);
                    /* try Cond; if fails jump to else */
                    emit_goal(left->children[0], uid * 10 + 1, "", else_lbl);
                    /* Cond succeeded: run Then -> γ */
                    emit_goal(left->children[1], uid * 10 + 2, γ, ω);
                    PL_C("    goto %s;\n", done_lbl);
                    /* else branch */
                    PL_C("%s:\n", else_lbl);
                    emit_goal(right, uid * 10 + 3, γ, ω);
                    PL_C("%s:;\n", done_lbl);
                } else {
                    /* Simple A ; B */
                    char else_lbl[LBUF], done_lbl[LBUF];
                    snprintf(else_lbl, LBUF, "disj%d_b", uid);
                    snprintf(done_lbl, LBUF, "disj%d_done", uid);
                    emit_goal(left,  uid * 10 + 1, γ, else_lbl);
                    PL_C("    goto %s;\n", done_lbl);
                    PL_C("%s:\n", else_lbl);
                    emit_goal(right, uid * 10 + 2, γ, ω);
                    PL_C("%s:;\n", done_lbl);
                }
                return;
            }

            /* ->/2 alone (if-then without else): Cond -> Then
             * If Cond fails → ω. Cut Cond after first solution. */
            if (strcmp(fn, "->") == 0 && arity == 2) {
                emit_goal(goal->children[0], uid * 10 + 1, "", ω);
                emit_goal(goal->children[1], uid * 10 + 2, γ, ω);
                return;
            }

            /* \+/1 — negation-as-failure */
            if ((strcmp(fn, "\\+") == 0 || strcmp(fn, "not") == 0) && arity == 1) {
                char naf_succ[LBUF], naf_fail[LBUF];
                snprintf(naf_succ, LBUF, "naf%d_s", uid);
                snprintf(naf_fail, LBUF, "naf%d_f", uid);
                int mu = pl_next_uid();
                PL_C("    { int _naf%d = trail_mark(&_trail);\n", mu);
                /* try goal in a sub-trail; if it succeeds → outer ω */
                /* We implement via a temporary copy of trail */
                PL_C("      Trail _naf_tr%d = _trail;\n", mu);
                PL_C("      int _naf_ok%d = 0;\n", mu);
                /* emit child goal into a goto-label pair we catch */
                /* simplified: call as a function if it's a user predicate,
                 * or emit inline with flag capture */
                (void)naf_succ; (void)naf_fail;
                PL_C("      /* \\+ inline not yet fully supported - treat as opaque */\n");
                PL_C("      (void)_naf_ok%d;\n", mu);
                PL_C("    }\n");
                PG(γ); return;
            }

            /* functor/3 — term decomposition/construction */
            if (strcmp(fn, "functor") == 0 && arity == 3) {
                snprintf(lbl, LBUF, "functor%d_α", uid);
                PLG(lbl, NULL);
                int mu = pl_next_uid();
                PL_C("    { int _fm%d = trail_mark(&_trail);\n", mu);
                PL_C("      if (!pl_functor(");
                emit_term_val(goal->children[0]); PL_C(", ");
                emit_term_val(goal->children[1]); PL_C(", ");
                emit_term_val(goal->children[2]);
                PL_C(", &_trail)) { trail_unwind(&_trail, _fm%d); goto %s; } }\n",
                     mu, ω);
                PG(γ); return;
            }
            /* arg/3 */
            if (strcmp(fn, "arg") == 0 && arity == 3) {
                snprintf(lbl, LBUF, "arg%d_α", uid);
                PLG(lbl, NULL);
                int mu = pl_next_uid();
                PL_C("    { int _am%d = trail_mark(&_trail);\n", mu);
                PL_C("      if (!pl_arg(");
                emit_term_val(goal->children[0]); PL_C(", ");
                emit_term_val(goal->children[1]); PL_C(", ");
                emit_term_val(goal->children[2]);
                PL_C(", &_trail)) { trail_unwind(&_trail, _am%d); goto %s; } }\n",
                     mu, ω);
                PG(γ); return;
            }
            /* =../2 — univ */
            if (strcmp(fn, "=..") == 0 && arity == 2) {
                snprintf(lbl, LBUF, "univ%d_α", uid);
                PLG(lbl, NULL);
                int mu = pl_next_uid();
                PL_C("    { int _uvm%d = trail_mark(&_trail);\n", mu);
                PL_C("      if (!pl_univ(");
                emit_term_val(goal->children[0]); PL_C(", ");
                emit_term_val(goal->children[1]);
                PL_C(", &_trail)) { trail_unwind(&_trail, _uvm%d); goto %s; } }\n",
                     mu, ω);
                PG(γ); return;
            }

            /* --- user-defined predicate call (resumable via _r) --- */
            {
                snprintf(lbl, LBUF, "call%d_α", uid);
                PLG(lbl, NULL);
                char fname[256];
                snprintf(fname, sizeof fname, "pl_%s_%d", safe_name(fn) + 2, arity);
                int cmu = pl_next_uid();
                /* _start tracks which clause to try next for backtracking */
                PL_C("    int _cs%d = 0;\n", cmu);
                PL_C("    { int _cm%d = trail_mark(&_trail);\n", cmu);
                PL_C("      int _cr%d = %s_r(", cmu, fname);
                for (int i = 0; i < arity; i++) {
                    emit_term_val(goal->children[i]); PL_C(", ");
                }
                PL_C("&_trail, _cs%d);\n", cmu);
                PL_C("      if (_cr%d < 0) { trail_unwind(&_trail, _cm%d); goto %s; }\n",
                     cmu, cmu, ω);
                PL_C("      _cs%d = _cr%d + 1;\n", cmu, cmu);  /* advance for next retry */
                PL_C("    }\n");
                PG(γ); return;
            }
        }

        /* ----------------------------------------------------------------
         * E_TRAIL_MARK / E_TRAIL_UNWIND — runtime bookkeeping
         * ---------------------------------------------------------------- */
        case E_TRAIL_MARK:
            PL_C("    _mark = trail_mark(&_trail);\n");
            PG(γ); return;
        case E_TRAIL_UNWIND:
            PL_C("    trail_unwind(&_trail, _mark);\n");
            PG(γ); return;

        default:
            /* unknown node — skip */
            PG(γ); return;
    }
}

/* =========================================================================
 * is_user_call — true for user-defined predicates that need retry loop
 * ======================================================================= */
static int is_user_call(EXPR_t *goal) {
    if (!goal || goal->kind != E_FNC || !goal->sval) return 0;
    const char *fn = goal->sval;
    static const char *builtins[] = {
        "true","fail","halt","nl","write","writeln","print","tab","is",
        "<",">","=<",">=","=:=","=\\=","=","\\=","==","\\==",
        "@<","@>","@=<","@>=",
        "var","nonvar","atom","integer","float","compound","atomic","is_list",
        "functor","arg","=..","\\+","not",",",";","->",
        NULL
    };
    for (int i = 0; builtins[i]; i++)
        if (strcmp(fn, builtins[i]) == 0) return 0;
    return 1;
}

/* =========================================================================
 * emit_body — chain N goals with Proebsting retry wiring
 *
 * For user-defined predicates: wrap call + suffix in for(;;) retry loop.
 *   suffix.fail → retry_top  (Proebsting: E2.fail → E1.resume)
 * For deterministic goals: linear chain, fail → outer ω.
 * ======================================================================= */
static void emit_body(EXPR_t **goals, int ngoals, int base_uid,
                      const char *γ, const char *ω) {
    if (ngoals == 0) { PG(γ); return; }

    for (int i = 0; i < ngoals; i++) {
        EXPR_t *g = goals[i];

        if (is_user_call(g)) {
            const char *fn = g->sval;
            int arity = g->nchildren;
            char fname[256];
            snprintf(fname, sizeof fname, "pl_%s_%d", safe_name(fn) + 2, arity);
            int cmu = pl_next_uid();
            char retry_lbl[LBUF], call_lbl[LBUF];
            snprintf(call_lbl,  LBUF, "call%d_α", cmu);
            snprintf(retry_lbl, LBUF, "retry%d",  cmu);

            PLG(call_lbl, NULL);
            PL_C("    int _cs%d = 0, _cr%d;\n", cmu, cmu);
            PL_C("    int _cm%d = trail_mark(&_trail);\n", cmu);
            PL_C("%s:\n", retry_lbl);
            PL_C("    trail_unwind(&_trail, _cm%d);\n", cmu);
            PL_C("    _cr%d = %s_r(", cmu, fname);
            for (int j = 0; j < arity; j++) {
                emit_term_val(g->children[j]); PL_C(", ");
            }
            PL_C("&_trail, _cs%d);\n", cmu);
            PL_C("    if (_cr%d < 0) goto %s;\n", cmu, ω);
            PL_C("    _cs%d = _cr%d + 1;\n", cmu, cmu);

            if (i + 1 < ngoals) {
                /* Find whether suffix contains a cut.
                 * Goals before the cut backtrack into this call (ω=retry_lbl).
                 * Goals after the cut have committed — they must fail to the
                 * outer ω, not back into the retry loop (Proebsting: cut seals β). */
                int cut_pos = -1;
                for (int k = i + 1; k < ngoals; k++) {
                    if (goals[k] && goals[k]->kind == E_CUT) { cut_pos = k; break; }
                }
                if (cut_pos < 0) {
                    /* No cut in suffix — normal Proebsting wiring */
                    emit_body(goals + i + 1, ngoals - i - 1,
                              pl_next_uid(), γ, retry_lbl);
                } else {
                    /* Emit goals up to and including cut with ω=retry_lbl,
                     * then goals after cut with ω=outer ω (cut has committed). */
                    int pre_len  = cut_pos - i;          /* includes the cut itself */
                    int post_len = ngoals - cut_pos - 1; /* goals after cut */
                    char post_γ[LBUF];
                    snprintf(post_γ, LBUF, "g%d_γ", pl_next_uid());
                    emit_body(goals + i + 1, pre_len,
                              pl_next_uid(), post_len > 0 ? post_γ : γ, retry_lbl);
                    if (post_len > 0) {
                        PL_C("%s:\n", post_γ);
                        emit_body(goals + cut_pos + 1, post_len,
                                  pl_next_uid(), γ, ω);
                    }
                }
            } else {
                PG(γ);
            }
            return;
        }

        /* Deterministic goal */
        char next_lbl[LBUF];
        if (i + 1 < ngoals)
            snprintf(next_lbl, LBUF, "g%d_γ", pl_next_uid());
        else
            snprintf(next_lbl, LBUF, "%s", γ);

        emit_goal(g, pl_next_uid(), next_lbl, ω);
        if (i + 1 < ngoals) PL_C("%s:\n", next_lbl);
    }
}

/* =========================================================================
 * emit_clause — one E_CLAUSE node
 *
 * Layout of E_CLAUSE children (from prolog_lower.c):
 *   children[0..n_args-1]  = head argument terms
 *   children[n_args..]     = body goal terms
 *
 * Generates:
 *   PRED_N_α:   (trail mark already saved by E_CHOICE emitter)
 *       unify arg0 with head_arg0; failure → next_label
 *       unify arg1 with head_arg1; failure → next_label
 *       ...body goals...
 *       goto outer_γ
 *   (fall through → next_label)
 * ======================================================================= */
static void emit_clause(EXPR_t *ec, int clause_idx,
                        const char *pred_α,  /* label for this clause's α */
                        const char *next_label,  /* β of this clause = α of next */
                        const char *γ,       /* success destination */
                        const char *ω,       /* failure after all clauses */
                        int n_args) {
    int uid = pl_next_uid();

    /* α entry label */
    PLG(pred_α, NULL);

    /* Unify each head argument.
     * ec->children[0..n_args-1] are the head arg patterns.
     * The actual call arguments are passed as _arg0, _arg1, ... from the
     * caller (set up by E_CHOICE emitter in the function signature). */
    for (int i = 0; i < n_args && i < ec->nchildren; i++) {
        EXPR_t *head_arg = ec->children[i];
        char unify_fail[LBUF];
        snprintf(unify_fail, LBUF, "%s", next_label);  /* head mismatch → try next */
        int mu = pl_next_uid();
        PL_C("    { int _hm%d = trail_mark(&_trail);\n", mu);
        PL_C("      if (!unify(_arg%d, ", i);
        emit_term_val(head_arg);
        PL_C(", &_trail)) { trail_unwind(&_trail, _hm%d); goto %s; } }\n",
             mu, unify_fail);
    }

    /* Body goals */
    int nbody = ec->nchildren - n_args;
    EXPR_t **body = ec->children + n_args;

    /* Check for cut in body — if present, on backtrack we go to ω not β */
    int has_cut = 0;
    for (int i = 0; i < nbody; i++)
        if (body[i] && body[i]->kind == E_CUT) { has_cut = 1; break; }
    (void)has_cut;

    char body_γ[LBUF], body_ω[LBUF];
    snprintf(body_γ, LBUF, "%s", γ);
    snprintf(body_ω, LBUF, "%s", ω);

    if (nbody == 0) {
        PG(γ);
    } else {
        emit_body(body, nbody, uid * 1000 + clause_idx, body_γ, body_ω);
    }
}

/* =========================================================================
 * emit_choice — one E_CHOICE node (all clauses for one predicate)
 *
 * Generates a C function:
 *
 *   int pl_FUNCTOR_ARITY(Term *_arg0, Term *_arg1, ..., Trail *_tr, int *_cut_out)
 *   {
 *       Trail _trail = *_tr;
 *       int   _mark  = trail_mark(&_trail);
 *       int   _cut   = 0;
 *       Term *_env[N_VARS];  // all NULL initially
 *
 *   P_FOO_α:   // clause 1 head unify
 *       ...
 *       goto P_FOO_γ;
 *
 *   P_FOO_β:   // clause 2 head unify (only if clause 1 failed)
 *       trail_unwind(&_trail, _mark);
 *       ...
 *       goto P_FOO_γ;
 *
 *   P_FOO_ω:
 *       trail_unwind(&_trail, _mark);
 *       *_tr = _trail;
 *       return 0;
 *
 *   P_FOO_γ:
 *       *_tr = _trail;
 *       return 1;
 *   }
 *
 * Cut seals β: on E_CUT in body, _cut=1, and β falls through to ω.
 * ======================================================================= */
static void emit_choice(EXPR_t *choice) {
    if (!choice || choice->kind != E_CHOICE) return;

    const char *pred = choice->sval ? choice->sval : "unknown/0";
    int nclauses = choice->nchildren;

    /* Parse "functor/arity" */
    char functor[128];
    int arity = 0;
    strncpy(functor, pred, sizeof functor - 1);
    functor[sizeof functor - 1] = '\0';
    char *slash = strrchr(functor, '/');
    if (slash) { arity = atoi(slash + 1); *slash = '\0'; }

    /* Find max n_vars across all clauses */
    int max_vars = 0;
    for (int ci = 0; ci < nclauses; ci++) {
        EXPR_t *ec = choice->children[ci];
        if (ec && ec->ival > max_vars) max_vars = (int)ec->ival;
    }

    char sfn[128];
    snprintf(sfn, sizeof sfn, "pl_%s_%d", safe_name(functor) + 2, arity);

    /* -----------------------------------------------------------------------
     * Emit the resumable function:
     *   int pl_F_N(arg0..argN-1, Trail *_tr, int _start)
     *
     * _start == clause index to begin trying from (0 = first call, β = retry).
     * Returns: next _start to use if caller wants another solution (β port),
     *          or -1 when all clauses exhausted (ω port).
     * On each successful return (≥0 or via the γ path) the Trail carries
     * the bindings made.  Caller saves trail mark before calling; on retry
     * it unwinds to that mark, then calls again with the returned _start.
     *
     * Single-solution wrapper (backward compat):
     *   int pl_F_N(args, Trail*)  { int _s=0; int r=pl_F_N_r(args,tr,&_s); return r>0; }
     * ----------------------------------------------------------------------- */
    PL_C("\n/* predicate %s/%d — %d clause(s) */\n", functor, arity, nclauses);

    /* --- resumable core --- */
    PL_C("static int %s_r(", sfn);
    for (int i = 0; i < arity; i++) PL_C("Term *_arg%d, ", i);
    PL_C("Trail *_tr, int _start) {\n");
    PL_C("    Trail _trail = *_tr;\n");
    PL_C("    int   _mark  = trail_mark(&_trail);\n");
    PL_C("    int   _cut   = 0;\n");
    if (max_vars > 0) {
        PL_C("    Term *_env[%d];\n", max_vars);
        PL_C("    for (int _i=0;_i<%d;_i++) _env[_i]=term_new_var(_i);\n", max_vars);
    }
    PL_C("    switch (_start) {\n");

    /* Build per-clause labels */
    char **c_α = malloc(nclauses * sizeof(char *));
    for (int ci = 0; ci < nclauses; ci++) {
        c_α[ci] = malloc(LBUF);
        snprintf(c_α[ci], LBUF, "cl%d_%d_α", pl_uid_ctr + 1, ci);
    }
    char ω_lbl[LBUF], γ_lbl_base[LBUF];
    snprintf(ω_lbl,      LBUF, "pred_%d_ω", pl_uid_ctr + 1);
    snprintf(γ_lbl_base, LBUF, "pred_%d_γ", pl_uid_ctr + 1);

    /* Per-clause γ labels that return the clause index */
    char **c_γ = malloc(nclauses * sizeof(char *));
    for (int ci = 0; ci < nclauses; ci++) {
        c_γ[ci] = malloc(LBUF);
        snprintf(c_γ[ci], LBUF, "pred_%d_γ%d", pl_uid_ctr + 1, ci);
    }

    PL_C("    case 0:;\n");

    for (int ci = 0; ci < nclauses; ci++) {
        EXPR_t *ec = choice->children[ci];
        if (!ec) continue;

        const char *next = (ci + 1 < nclauses) ? c_α[ci + 1] : ω_lbl;

        if (ci > 0) {
            PL_C("%s:\n", c_α[ci]);
            PL_C("    case %d:;\n", ci);
            PL_C("    if (_cut) goto %s;\n", ω_lbl);
            PL_C("    trail_unwind(&_trail, _mark);\n");
            if (max_vars > 0)
                PL_C("    for (int _i=0;_i<%d;_i++) _env[_i]=term_new_var(_i);\n", max_vars);
        }

        emit_clause(ec, ci,
                    ci == 0 ? c_α[ci] : "",
                    next, c_γ[ci], ω_lbl, arity);
    }
    PL_C("    }\n");

    /* ω */
    PL_C("%s:\n", ω_lbl);
    PL_C("    trail_unwind(&_trail, _mark);\n");
    PL_C("    *_tr = _trail; return -1;\n");

    /* Per-clause γ — return clause index so caller knows where to retry from */
    for (int ci = 0; ci < nclauses; ci++) {
        PL_C("%s:\n", c_γ[ci]);
        PL_C("    *_tr = _trail; return %d;\n", ci);
    }
    PL_C("}\n");

    /* --- single-shot wrapper --- */
    PL_C("int %s(", sfn);
    for (int i = 0; i < arity; i++) PL_C("Term *_arg%d, ", i);
    PL_C("Trail *_tr) {\n");
    PL_C("    return %s_r(", sfn);
    for (int i = 0; i < arity; i++) PL_C("_arg%d, ", i);
    PL_C("_tr, 0) >= 0;\n}\n");

    for (int ci = 0; ci < nclauses; ci++) { free(c_α[ci]); free(c_γ[ci]); }
    free(c_α); free(c_γ);
}

/* =========================================================================
 * emit_directive — :- initialization(main) and similar
 * ======================================================================= */
static void emit_directive(EXPR_t *e) {
    if (!e) return;
    if (e->kind == E_FNC && e->sval) {
        /* :- initialization(main) */
        if (strcmp(e->sval, "initialization") == 0 && e->nchildren == 1) {
            EXPR_t *goal = e->children[0];
            if (goal && goal->kind == E_QLIT && goal->sval) {
                /* stored for main() emission */
                PL_C("/* directive: initialization(%s) — called from main() */\n",
                     goal->sval);
            }
        }
    }
}

/* =========================================================================
 * pl_emit — main entry point
 *
 * Called by the sno2c driver when -pl flag is active.
 * ======================================================================= */
void pl_emit(Program *prog, FILE *f) {
    pl_out = f;
    pl_uid_ctr = 0;

    emit_pl_preamble();

    /* Forward-declare all predicate functions (resumable _r + wrapper) */
    PL_C("/* --- forward declarations --- */\n");
    for (STMT_t *s = prog->head; s; s = s->next) {
        EXPR_t *e = s->subject;
        if (!e || e->kind != E_CHOICE) continue;
        const char *pred = e->sval ? e->sval : "?/0";
        char functor[128]; int arity = 0;
        strncpy(functor, pred, sizeof functor - 1);
        functor[sizeof functor - 1] = '\0';
        char *slash = strrchr(functor, '/');
        if (slash) { arity = atoi(slash + 1); *slash = '\0'; }
        char sfn[128];
        snprintf(sfn, sizeof sfn, "pl_%s_%d", safe_name(functor) + 2, arity);
        /* resumable */
        PL_C("static int %s_r(", sfn);
        for (int i = 0; i < arity; i++) PL_C("Term *_arg%d, ", i);
        PL_C("Trail *_tr, int _start);\n");
        /* wrapper */
        PL_C("static int %s(", sfn);
        for (int i = 0; i < arity; i++) PL_C("Term *_arg%d, ", i);
        PL_C("Trail *_tr);\n");
    }
    PL_C("\n");

    /* Emit directives */
    for (STMT_t *s = prog->head; s; s = s->next) {
        EXPR_t *e = s->subject;
        if (!e || e->kind == E_CHOICE) continue;
        emit_directive(e);
    }

    /* Emit one function per E_CHOICE */
    for (STMT_t *s = prog->head; s; s = s->next) {
        EXPR_t *e = s->subject;
        if (!e || e->kind != E_CHOICE) continue;
        emit_choice(e);
    }

    /* Emit main() */
    PL_C("\nint main(void) {\n");
    PL_C("    prolog_atom_init();\n");
    PL_C("    Trail _tr;\n");
    PL_C("    trail_init(&_tr);\n");
    /* Find initialization directive — goal child is E_FNC or E_QLIT */
    const char *init_pred = "main";
    for (STMT_t *s = prog->head; s; s = s->next) {
        EXPR_t *e = s->subject;
        if (e && e->kind == E_FNC && e->sval &&
            strcmp(e->sval, "initialization") == 0 &&
            e->nchildren == 1 && e->children[0]) {
            EXPR_t *goal = e->children[0];
            if ((goal->kind == E_FNC || goal->kind == E_QLIT) && goal->sval)
                init_pred = goal->sval;
        }
    }
    PL_C("    pl_%s_0(&_tr);\n", safe_name(init_pred) + 2);
    PL_C("    return 0;\n");
    PL_C("}\n");
}
