/*
 * pl_builtin.c — Prolog builtin predicate implementations
 *
 * write/1    — print a term to stdout
 * writeln/1  — print a term + newline
 * functor/3  — decompose/construct term head
 * arg/3      — nth argument of compound
 * =../2      — univ: Term =.. [Functor|Args]
 * read/1     — stub (returns fail for now)
 *
 * These are called from the code generated by pl_emit.c.
 */

#include "prolog_builtin.h"
#include "prolog_atom.h"
#include "prolog_runtime.h"
#include "term.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

/* =========================================================================
 * pl_write — print a term to stdout
 * ======================================================================= */
void pl_write(Term *t) {
    t = term_deref(t);
    if (!t) { printf("[]"); return; }
    switch (t->tag) {
        case TT_ATOM: {
            const char *name = prolog_atom_name(t->atom_id);
            if (!name) name = "?";
            /* Quote atoms that need it (contain spaces or start with upper) */
            int needs_quote = 0;
            if (name[0] && (isupper((unsigned char)name[0]) || name[0] == '_'))
                needs_quote = 1;
            for (const char *p = name; *p && !needs_quote; p++)
                if (!isalnum((unsigned char)*p) && *p != '_')
                    needs_quote = 1;
            if (needs_quote && name[0] != '[') {
                /* Actually: standard Prolog doesn't quote atoms in write/1,
                 * only in writeq/1.  Use writeq behaviour for clarity. */
            }
            printf("%s", name);
            break;
        }
        case TT_VAR:
            /* Unbound variable — print as _GN */
            printf("_G%d", t->var_slot);
            break;
        case TT_INT:
            printf("%ld", t->ival);
            break;
        case TT_FLOAT:
            printf("%g", t->fval);
            break;
        case TT_COMPOUND: {
            const char *fn = prolog_atom_name(t->compound.functor);
            if (!fn) fn = "?";
            /* List notation: '.'(H, T) -> [H|T] */
            if (t->compound.functor == ATOM_DOT && t->compound.arity == 2) {
                printf("[");
                pl_write(t->compound.args[0]);
                Term *tail = term_deref(t->compound.args[1]);
                while (tail && tail->tag == TT_COMPOUND &&
                       tail->compound.functor == ATOM_DOT &&
                       tail->compound.arity == 2) {
                    printf(",");
                    pl_write(tail->compound.args[0]);
                    tail = term_deref(tail->compound.args[1]);
                }
                if (tail && tail->tag == TT_ATOM && tail->atom_id == ATOM_NIL) {
                    /* clean list end */
                } else {
                    printf("|");
                    pl_write(tail);
                }
                printf("]");
                break;
            }
            /* Operator notation for common binary/unary ops */
            struct { const char *name; int arity; } ops[] = {
                {"+",2},{"-",2},{"*",2},{"/",2},{"//",2},{"mod",2},
                {"<",2},{">",2},{"=<",2},{">=",2},{"=:=",2},{"=\\=",2},
                {"=",2},{"\\=",2},{"is",2},{":-",2},{",",2},{";",2},
                {"-",1},{"\\+",1},
                {NULL,0}
            };
            int is_op = 0;
            for (int i = 0; ops[i].name; i++) {
                if (strcmp(fn, ops[i].name) == 0 && t->compound.arity == ops[i].arity) {
                    is_op = 1;
                    if (ops[i].arity == 2) {
                        printf("(");
                        pl_write(t->compound.args[0]);
                        printf("%s", fn);
                        pl_write(t->compound.args[1]);
                        printf(")");
                    } else {
                        printf("%s", fn);
                        pl_write(t->compound.args[0]);
                    }
                    break;
                }
            }
            if (!is_op) {
                printf("%s(", fn);
                for (int i = 0; i < t->compound.arity; i++) {
                    if (i) printf(",");
                    pl_write(t->compound.args[i]);
                }
                printf(")");
            }
            break;
        }
        case TT_REF:
            pl_write(t->ref);  /* should not happen after term_deref */
            break;
    }
}

void pl_writeln(Term *t) {
    pl_write(t);
    printf("\n");
}

/* =========================================================================
 * pl_functor — functor(Term, Name, Arity)
 *
 * Rung-9 builtin.  If Term is bound:
 *   atom:     Name=atom_name, Arity=0
 *   compound: Name=functor_atom, Arity=n
 *   integer:  Name=integer, Arity=0
 * If Term is unbound and Name+Arity are bound: construct the term.
 * ======================================================================= */
int pl_functor(Term *t, Term *name, Term *arity, Trail *tr) {
    t     = term_deref(t);
    name  = term_deref(name);
    arity = term_deref(arity);

    if (t && t->tag != TT_VAR) {
        /* Decompose mode */
        Term *name_term  = NULL;
        Term *arity_term = NULL;
        switch (t->tag) {
            case TT_ATOM:
                name_term  = term_new_atom(t->atom_id);
                arity_term = term_new_int(0);
                break;
            case TT_INT:
                name_term  = term_new_int(t->ival);
                arity_term = term_new_int(0);
                break;
            case TT_FLOAT:
                name_term  = term_new_float(t->fval);
                arity_term = term_new_int(0);
                break;
            case TT_COMPOUND:
                name_term  = term_new_atom(t->compound.functor);
                arity_term = term_new_int(t->compound.arity);
                break;
            default:
                return 0;
        }
        int mark = trail_mark(tr);
        if (!unify(name, name_term, tr) || !unify(arity, arity_term, tr)) {
            trail_unwind(tr, mark);
            return 0;
        }
        return 1;
    } else {
        /* Construct mode: Name and Arity must be bound */
        if (!name || name->tag == TT_VAR) return 0;
        if (!arity || arity->tag != TT_INT) return 0;
        long ar = arity->ival;
        Term *new_t;
        if (ar == 0) {
            if (name->tag == TT_ATOM) new_t = term_new_atom(name->atom_id);
            else if (name->tag == TT_INT) new_t = term_new_int(name->ival);
            else return 0;
        } else {
            if (name->tag != TT_ATOM) return 0;
            /* Build compound with unbound var args */
            Term **args = malloc(ar * sizeof(Term *));
            for (int i = 0; i < ar; i++) args[i] = term_new_var(i);
            new_t = term_new_compound(name->atom_id, (int)ar, args);
            free(args);
        }
        int mark = trail_mark(tr);
        if (!unify(t, new_t, tr)) {
            trail_unwind(tr, mark);
            return 0;
        }
        return 1;
    }
}

/* =========================================================================
 * pl_arg — arg(N, Term, Arg)
 * ======================================================================= */
int pl_arg(Term *n, Term *compound, Term *arg, Trail *tr) {
    n        = term_deref(n);
    compound = term_deref(compound);

    if (!n || n->tag != TT_INT) return 0;
    if (!compound || compound->tag != TT_COMPOUND) return 0;
    long idx = n->ival;  /* 1-based */
    if (idx < 1 || idx > compound->compound.arity) return 0;

    int mark = trail_mark(tr);
    if (!unify(arg, compound->compound.args[idx - 1], tr)) {
        trail_unwind(tr, mark);
        return 0;
    }
    return 1;
}

/* =========================================================================
 * pl_univ — Term =.. List  (univ / =..)
 *
 * foo(a,b) =.. [foo, a, b]
 * foo      =.. [foo]
 * ======================================================================= */

/* Build a Prolog list from args array */
static Term *make_list(int n, Term **items) {
    Term *tail = term_new_atom(ATOM_NIL);
    for (int i = n - 1; i >= 0; i--) {
        Term *args[2] = { items[i], tail };
        tail = term_new_compound(ATOM_DOT, 2, args);
    }
    return tail;
}

/* Count list length; return -1 if not a proper list */
static int list_len(Term *t) {
    int n = 0;
    while (1) {
        t = term_deref(t);
        if (!t) return -1;
        if (t->tag == TT_ATOM && t->atom_id == ATOM_NIL) return n;
        if (t->tag != TT_COMPOUND || t->compound.functor != ATOM_DOT ||
            t->compound.arity != 2) return -1;
        n++;
        t = t->compound.args[1];
    }
}

int pl_univ(Term *t, Term *list, Trail *tr) {
    t    = term_deref(t);
    list = term_deref(list);

    if (t && t->tag != TT_VAR) {
        /* Decompose: T =.. L */
        Term *result;
        if (t->tag == TT_ATOM) {
            Term *items[1] = { term_new_atom(t->atom_id) };
            result = make_list(1, items);
        } else if (t->tag == TT_INT) {
            Term *items[1] = { term_new_int(t->ival) };
            result = make_list(1, items);
        } else if (t->tag == TT_COMPOUND) {
            int arity = t->compound.arity;
            Term **items = malloc((arity + 1) * sizeof(Term *));
            items[0] = term_new_atom(t->compound.functor);
            for (int i = 0; i < arity; i++) items[i + 1] = t->compound.args[i];
            result = make_list(arity + 1, items);
            free(items);
        } else return 0;
        int mark = trail_mark(tr);
        if (!unify(list, result, tr)) { trail_unwind(tr, mark); return 0; }
        return 1;
    } else {
        /* Construct: T =.. L, L must be bound */
        if (!list || list->tag != TT_COMPOUND || list->compound.functor != ATOM_DOT)
            return 0;
        int len = list_len(list);
        if (len < 1) return 0;
        /* Extract functor and args */
        Term *head_item = term_deref(list->compound.args[0]);
        if (!head_item || head_item->tag != TT_ATOM) return 0;
        int functor_id = head_item->atom_id;
        int arity = len - 1;
        Term *new_t;
        if (arity == 0) {
            new_t = term_new_atom(functor_id);
        } else {
            Term **args = malloc(arity * sizeof(Term *));
            Term *cur = term_deref(list->compound.args[1]);
            for (int i = 0; i < arity; i++) {
                args[i] = term_deref(cur->compound.args[0]);
                cur = term_deref(cur->compound.args[1]);
            }
            new_t = term_new_compound(functor_id, arity, args);
            free(args);
        }
        int mark = trail_mark(tr);
        if (!unify(t, new_t, tr)) { trail_unwind(tr, mark); return 0; }
        return 1;
    }
}

/* =========================================================================
 * pl_read — stub: always fails
 * ======================================================================= */
int pl_read(Term *result, Trail *tr) {
    (void)result; (void)tr;
    return 0;  /* not implemented in M-PROLOG-R1 */
}

/* =========================================================================
 * Arithmetic evaluation — is/2
 * ======================================================================= */

static int _aid_plus=-1, _aid_minus=-1, _aid_times=-1, _aid_div=-1, _aid_mod=-1;
static void arith_atoms_init(void) {
    if (_aid_plus >= 0) return;
    _aid_plus  = prolog_atom_intern("+");
    _aid_minus = prolog_atom_intern("-");
    _aid_times = prolog_atom_intern("*");
    _aid_div   = prolog_atom_intern("/");
    _aid_mod   = prolog_atom_intern("mod");
}

long pl_eval_arith(Term *t) {
    arith_atoms_init();
    t = term_deref(t);
    if (!t) return 0;
    switch (t->tag) {
        case TT_INT: return t->ival;
        case TT_FLOAT: return (long)t->fval;
        case TT_COMPOUND: {
            int f = t->compound.functor;
            int a = t->compound.arity;
            if (a == 2) {
                long l = pl_eval_arith(t->compound.args[0]);
                long r = pl_eval_arith(t->compound.args[1]);
                if (f == _aid_plus)  return l + r;
                if (f == _aid_minus) return l - r;
                if (f == _aid_times) return l * r;
                if (f == _aid_div)   return r ? l / r : 0;
                if (f == _aid_mod)   return r ? l % r : 0;
            }
            if (a == 1) {
                long v = pl_eval_arith(t->compound.args[0]);
                if (f == _aid_minus) return -v;
            }
            return 0;
        }
        default: return 0;
    }
}

/* is/2: Result is Expr — unify Result with evaluated Expr */
int pl_is(Term *result, Term *expr, Trail *trail) {
    long val = pl_eval_arith(expr);
    Term *res_term = term_new_int(val);
    return unify(result, res_term, trail);
}

/* Numeric comparisons */
int pl_num_lt(Term *a, Term *b)  { return pl_eval_arith(a) <  pl_eval_arith(b); }
int pl_num_gt(Term *a, Term *b)  { return pl_eval_arith(a) >  pl_eval_arith(b); }
int pl_num_le(Term *a, Term *b)  { return pl_eval_arith(a) <= pl_eval_arith(b); }
int pl_num_ge(Term *a, Term *b)  { return pl_eval_arith(a) >= pl_eval_arith(b); }
int pl_num_eq(Term *a, Term *b)  { return pl_eval_arith(a) == pl_eval_arith(b); }
int pl_num_ne(Term *a, Term *b)  { return pl_eval_arith(a) != pl_eval_arith(b); }

/* Type-test builtins — return 1 (true) or 0 (false), no Trail needed */
int pl_atom(Term *t)     { t = term_deref(t); return t && t->tag == TT_ATOM; }
int pl_integer(Term *t)  { t = term_deref(t); return t && t->tag == TT_INT; }
int pl_is_float(Term *t) { t = term_deref(t); return t && t->tag == TT_FLOAT; }
int pl_var(Term *t)      { t = term_deref(t); return !t || t->tag == TT_VAR; }
int pl_nonvar(Term *t)   { t = term_deref(t); return t && t->tag != TT_VAR; }
int pl_compound(Term *t) { t = term_deref(t); return t && t->tag == TT_COMPOUND; }
int pl_callable(Term *t) { t = term_deref(t); return t && (t->tag == TT_ATOM || t->tag == TT_COMPOUND); }
