/* generated by sno2c -trampoline */
#include "trampoline.h"
#include "runtime_shim.h"

/* --- global SNOBOL4 variables --- */
static SnoVal _I = {0};

/* --- block forward declarations --- */
static void *block_START(void);
static void *block_END(void);
static void *block__LOOP(void);
static void *block__DONE(void);

static SnoVal _sno_fn_Shift(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_Reduce(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_InitStack(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_Push(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_Pop(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_Top(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_InitCounter(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_PushCounter(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_IncCounter(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_DecCounter(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_PopCounter(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_TopCounter(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_InitBegTag(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_PushBegTag(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_PopBegTag(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_TopBegTag(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_DumpBegTag(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_InitEndTag(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_PushEndTag(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_PopEndTag(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_TopEndTag(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_DumpEndTag(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_shift_(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_reduce_(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_pop_(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_nPush_(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_nInc_(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_nDec_(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_nTop_(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_nPop_(SnoVal *_args, int _nargs);


static char _tramp_sentinel_1;
#define _tramp_next_1 ((void*)&_tramp_sentinel_1)
static void *stmt_1(void) { /* line 1 */
/* line 1 */
SnoVal _v2 = vint(1);
int _ok2 = !IS_FAIL(_v2);
if(_ok2) {
set(_I, _v2);
var_set("I", _I);
}
    return (void*)_tramp_next_1;
}

static char _tramp_sentinel_3;
#define _tramp_next_3 ((void*)&_tramp_sentinel_3)
static void *stmt_2(void) { /* line 2 label:LOOP */
/* line 2 */
_L_LOOP:;
SnoVal _v4 = get(_I);
int _ok4 = !IS_FAIL(_v4);
if(_ok4) {
var_set("OUTPUT", _v4);
}
    return (void*)_tramp_next_3;
}

static char _tramp_sentinel_5;
#define _tramp_next_5 ((void*)&_tramp_sentinel_5)
static void *stmt_3(void) { /* line 3 */
/* line 3 */
SnoVal _v6 = add(get(_I),vint(1));
int _ok6 = !IS_FAIL(_v6);
if(_ok6) {
set(_I, _v6);
var_set("I", _I);
}
    return (void*)_tramp_next_5;
}

static char _tramp_sentinel_7;
#define _tramp_next_7 ((void*)&_tramp_sentinel_7)
static void *stmt_4(void) { /* line 4 */
/* line 4 */
SnoVal _v8 = aply("EQ",(SnoVal[]){get(_I),vint(4)},2);
int _ok8 = !IS_FAIL(_v8);
    if(_ok8) return (void*)block__DONE;
    return (void*)_tramp_next_7;
}

static char _tramp_sentinel_9;
#define _tramp_next_9 ((void*)&_tramp_sentinel_9)
static void *stmt_5(void) { /* line 5 */
/* line 5 */
    return (void*)block__LOOP;
}

static char _tramp_sentinel_10;
#define _tramp_next_10 ((void*)&_tramp_sentinel_10)
static void *stmt_6(void) { /* line 6 label:DONE */
/* line 6 */
_L_DONE:;
SnoVal _v11 = strv("done");
int _ok11 = !IS_FAIL(_v11);
if(_ok11) {
var_set("OUTPUT", _v11);
}
    return (void*)_tramp_next_10;
}

/* --- block functions --- */
static void *block_START(void) {
    { void *_r = stmt_1();
      if (_r != _tramp_next_1) return _r; }
    return block__LOOP; /* fall into next block */
}

static void *block__LOOP(void) {
    { void *_r = stmt_2();
      if (_r != _tramp_next_3) return _r; }
    { void *_r = stmt_3();
      if (_r != _tramp_next_5) return _r; }
    { void *_r = stmt_4();
      if (_r != _tramp_next_7) return _r; }
    { void *_r = stmt_5();
      if (_r != _tramp_next_9) return _r; }
    return block__DONE; /* fall into next block */
}

static void *block__DONE(void) {
    { void *_r = stmt_6();
      if (_r != _tramp_next_10) return _r; }
    return block_END;
}

static void *block_END(void) { return NULL; }

int main(void) {
    ini();
    var_register("I", &_I);
    var_sync_registered();


    trampoline_run(block_START);
    return 0;
}
