/* generated by sno2c -trampoline */
#include "trampoline.h"
#include "runtime_shim.h"

/* --- global SNOBOL4 variables --- */
static SnoVal _DOUBLE = {0};
static SnoVal _X = {0};

/* --- block forward declarations --- */
static void *block_START(void);
static void *block_END(void);
static void *block__DOUBLE(void);
static void *block__ENDDOUBLE(void);

static SnoVal _sno_fn_DOUBLE(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_Shift(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_Reduce(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_InitStack(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_Push(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_Pop(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_Top(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_InitCounter(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_PushCounter(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_IncCounter(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_DecCounter(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_PopCounter(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_TopCounter(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_InitBegTag(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_PushBegTag(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_PopBegTag(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_TopBegTag(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_DumpBegTag(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_InitEndTag(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_PushEndTag(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_PopEndTag(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_TopEndTag(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_DumpEndTag(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_shift_(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_reduce_(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_pop_(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_nPush_(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_nInc_(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_nDec_(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_nTop_(SnoVal *_args, int _nargs);
static SnoVal _sno_fn_nPop_(SnoVal *_args, int _nargs);

static SnoVal _sno_fn_DOUBLE(SnoVal *_args, int _nargs) {
    SnoVal _saved__X = var_get("X"); /* save caller's hash value */

    jmp_buf _fn_abort_jmp;
    if (setjmp(_fn_abort_jmp) != 0) goto _SNO_ABORT_DOUBLE;
    push_abort_handler(&_fn_abort_jmp);

    SnoVal _DOUBLE = {0}; /* return value */
    SnoVal _X = (_nargs>0)?_args[0]:NULL_VAL;
    var_set("X", _X); /* install arg in hash */

/* line 2 */
_L_DOUBLE:;
SnoVal _v2 = add(get(_X),get(_X));
int _ok2 = !IS_FAIL(_v2);
if(_ok2) {
set(_DOUBLE, _v2);
var_set("DOUBLE", _DOUBLE);
}
    goto _SNO_RETURN_DOUBLE;
_SNO_NEXT_1:;
    goto _SNO_RETURN_DOUBLE;

_SNO_RETURN_DOUBLE:
    pop_abort_handler();
    var_set("X", _saved__X); /* restore caller's value */
    return get(_DOUBLE);
_SNO_FRETURN_DOUBLE:
    pop_abort_handler();
    var_set("X", _saved__X); /* restore caller's value */
    return FAIL_VAL;
_SNO_ABORT_DOUBLE:
    var_set("X", _saved__X); /* restore caller's value */
    return FAIL_VAL;
}


static char _tramp_sentinel_3;
#define _tramp_next_3 ((void*)&_tramp_sentinel_3)
static void *stmt_1(void) { /* line 3 label:ENDDOUBLE */
/* line 3 */
_L_ENDDOUBLE:;
    return (void*)_tramp_next_3;
}

static char _tramp_sentinel_4;
#define _tramp_next_4 ((void*)&_tramp_sentinel_4)
static void *stmt_2(void) { /* line 4 */
/* line 4 */
SnoVal _v5 = aply("DOUBLE",(SnoVal[]){vint(21)},1);
int _ok5 = !IS_FAIL(_v5);
if(_ok5) {
var_set("OUTPUT", _v5);
}
    return (void*)_tramp_next_4;
}

/* --- block functions --- */
static void *block_START(void) {
    { void *_r = stmt_1();
      if (_r != _tramp_next_3) return _r; }
    { void *_r = stmt_2();
      if (_r != _tramp_next_4) return _r; }
    return block_END;
}

static void *block_END(void) { return NULL; }

int main(void) {
    ini();
    var_register("DOUBLE", &_DOUBLE);
    var_register("X", &_X);
    var_sync_registered();

    define("DOUBLE(X)", _sno_fn_DOUBLE);

    trampoline_run(block_START);
    return 0;
}
