#!/usr/bin/env python3
"""wrap_snobol4.py — instrument snobol4.c with mon_enter/mon_exit hooks

For each C function definition found in snobol4.c, rename the body to
<NAME>_inner() and emit a thin wrapper <NAME>() that calls mon_enter/mon_exit
around the inner call.

Usage:
    python3 wrap_snobol4.py <input_snobol4.c> <output_wrapped.c>

The output file is a drop-in replacement for snobol4.c in the build.
Add mon_hooks.c and -I<ss-monitor-dir> to the compile command.

Strategy:
- snobol4.c uses a non-standard calling convention macro: each function is
  defined as e.g.  `static int GENVAR(ret_t retval) {`  or
  `LOCA1(ret_t retval) {`  — the macro expands to the real signature.
- We detect function definitions by lines matching: word followed by `(`
  at column 0 (or with `static int` prefix), with `{` on the same or next line.
- We do NOT parse C — we use the structural property that snobol4.c is
  machine-generated and highly regular.

Limitations:
- Functions that contain nested `{}` at depth 0 in the outer body are handled
  by brace-depth counting.
- Inline functions, macros that expand to definitions, and truly odd constructs
  may be missed — check the output for `_inner` coverage.
"""

import sys
import re
import os

# Pattern: function definition line at top level
# Matches:  GENVAR(ret_t retval) {
#           static int LOCA1(ret_t retval) {
#           void BEGIN(void) {
# Groups: (return_type_prefix, funcname, params)
FUNC_DEF = re.compile(
    r'^((?:static\s+)?(?:int|void|ret_t|lret_t|RESULT_t|int32_t|SilResult)\s+)?'
    r'([A-Za-z_][A-Za-z0-9_]*)\s*'
    r'(\([^)]*\))\s*\{?\s*$'
)

# Lines that look like function definitions but are NOT (macros, etc.)
SKIP_NAMES = {
    'if', 'while', 'for', 'switch', 'else', 'do',
    'sizeof', 'return', 'case', 'default',
    # snobol4.c internal macros that look like function calls at col 0
    'ENTRY', 'BRANCH', 'RETURN', 'PUSH', 'POP', 'SAVSTK',
    'D', 'D_A', 'D_V', 'D_F', 'D_PTR', 'S_L', 'S_A',
    'HASH', 'X_LOCSP', 'LEXEQ', 'APDSP', 'MOVD',
}

def is_func_def(line, lines, idx):
    """Return (prefix, name, params) if line looks like a function definition."""
    m = FUNC_DEF.match(line)
    if not m:
        return None
    name = m.group(2)
    if name in SKIP_NAMES:
        return None
    # Must be followed by a body — check for { on this line or next
    has_open = '{' in line
    if not has_open and idx + 1 < len(lines):
        next_stripped = lines[idx + 1].strip()
        has_open = next_stripped.startswith('{')
    if not has_open:
        return None
    prefix = m.group(1) or ''
    params = m.group(3)
    return (prefix.strip(), name, params)


def extract_return_type(prefix, name):
    """Best-effort: return the C return type string."""
    if prefix:
        return prefix.rstrip()
    # snobol4.c convention: unlabelled functions default to static int
    return 'static int'


def param_to_arg(params):
    """Convert '(ret_t retval, int x)' → 'retval, x' for the call site."""
    inner = params.strip('()').strip()
    if not inner or inner == 'void':
        return ''
    args = []
    for p in inner.split(','):
        p = p.strip()
        # last word is the arg name
        parts = p.split()
        if parts:
            args.append(parts[-1].lstrip('*'))
    return ', '.join(args)


def wrap_file(src_path, dst_path):
    with open(src_path, 'r', errors='replace') as f:
        lines = f.readlines()

    out = []
    # Prepend our header
    out.append('/* snobol4-wrapped.c — generated by wrap_snobol4.py */\n')
    out.append('/* DO NOT EDIT — regenerate with wrap_snobol4.py */\n')
    out.append('#include "mon_hooks.h"\n')
    out.append('\n')

    i = 0
    wrapped = 0
    skipped = 0

    while i < len(lines):
        line = lines[i]
        info = is_func_def(line.rstrip('\n'), lines, i)

        if info is None:
            out.append(line)
            i += 1
            continue

        prefix, name, params = info
        ret_type = extract_return_type(prefix, name)
        call_args = param_to_arg(params)

        # Collect the full function body by brace depth
        body_lines = []
        depth = 0
        j = i
        started = False
        while j < len(lines):
            bl = lines[j]
            body_lines.append(bl)
            for ch in bl:
                if ch == '{':
                    depth += 1
                    started = True
                elif ch == '}':
                    depth -= 1
            j += 1
            if started and depth == 0:
                break

        # Emit the inner (renamed) function
        inner_name = name + '_inner'
        # Replace first occurrence of name( with inner_name( in the first body line
        first = body_lines[0]
        first_inner = first.replace(name + params, inner_name + params, 1)
        if first_inner == first:
            # Try without params (name might span two lines)
            first_inner = first.replace(name + '(', inner_name + '(', 1)

        out.append(f'/* --- wrapped: {name} --- */\n')
        out.append(first_inner)
        for bl in body_lines[1:]:
            out.append(bl)
        out.append('\n')

        # Emit the wrapper
        # Determine if void return
        is_void = 'void' in ret_type and 'ret_t' not in ret_type

        # Wrapper must NOT be static — proc.h declares these as extern.
        # The _inner version keeps the original storage class.
        wrapper_ret = ret_type.replace('static ', '').strip()
        out.append(f'{wrapper_ret} {name}{params}\n')
        out.append('{\n')
        out.append(f'    mon_enter("{name}");\n')
        if is_void:
            out.append(f'    {inner_name}({call_args});\n')
            out.append(f'    mon_exit("{name}", "void");\n')
        else:
            out.append(f'    int _r = (int)({inner_name}({call_args}));\n')
            out.append(f'    char _rb[16]; snprintf(_rb,sizeof(_rb),"%d",_r);\n')
            out.append(f'    mon_exit("{name}", _rb);\n')
            out.append(f'    return ({wrapper_ret.split()[-1]})_r;\n')
        out.append('}\n\n')

        wrapped += 1
        i = j

    with open(dst_path, 'w') as f:
        f.writelines(out)

    print(f"wrap_snobol4.py: {wrapped} functions wrapped, {skipped} skipped")
    print(f"Output: {dst_path}")


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <snobol4.c> <snobol4-wrapped.c>")
        sys.exit(1)
    wrap_file(sys.argv[1], sys.argv[2])
