; generated by sno2c -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o mock_engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_set_capture
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
P_OUTPUT_ret_gamma       resq 1
P_OUTPUT_ret_omega       resq 1
dol_entry_FIRST          resq 1
brk3_saved               resq 1
len4_saved               resq 1
dol_entry_LAST           resq 1
rem6_saved               resq 1
seq_r8_alpha_saved       resq 1
cap_FIRST_buf            resb 256
cap_FIRST_len            resq 1
cap_LAST_buf             resb 256
cap_LAST_len             resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
                            PROG_INIT


;  PROGRAM BODY ========================================================================================================

                            GET_VAR     S_X
                            ASSIGN_STR  S_X, S_John_SP_Smith, L_sn_0
                            jmp         L_sn_0

; ======================================================================================================================

; ======================================================================================================================
L_sn_0:                     GET_VAR     S_X
                            SUBJ_FROM16

                            jmp         P_1_α

P_1_α:                      jmp         seq_l0_alpha ; SEQ
P_1_β:                      jmp         seq_r0_beta
seq_l0_alpha:               jmp         seq_l1_alpha ; SEQ
seq_l0_beta:                jmp         seq_r1_beta

seq_l1_alpha: ; DOL(FIRST $  FIRST)
                            DOL_SAVE    dol_entry_FIRST, cursor, dol2_child_alpha ; DOL α — save entry cursor
seq_l1_beta:                jmp         dol2_child_beta ; DOL β
dol2_child_alpha:           BREAK_ALPHA lit_str_1, 1, brk3_saved, cursor, subject_data, subject_len_val, dol2_gamma, dol2_omega ; BREAK α
dol2_child_beta:            BREAK_BETA  brk3_saved, cursor, dol2_omega ; BREAK β
dol2_gamma:                 DOL_CAPTURE dol_entry_FIRST, cursor, cap_FIRST_buf, cap_FIRST_len, subject_data, seq_r1_alpha ; DOL γ — capture span
dol2_omega:                 jmp         P_1_ω ; DOL ω — child failed
seq_r1_alpha:               LEN_ALPHA   1, len4_saved, cursor, subject_len_val, seq_r0_alpha, seq_l1_beta ; LEN(%ld)
seq_r1_beta:                LEN_BETA    len4_saved, cursor, seq_l1_beta ; LEN β

seq_r0_alpha: ; DOL(LAST $  LAST)
                            DOL_SAVE    dol_entry_LAST, cursor, dol5_child_alpha ; DOL α — save entry cursor
seq_r0_beta:                jmp         dol5_child_beta ; DOL β
dol5_child_alpha:           REM_ALPHA   rem6_saved, cursor, subject_len_val, dol5_gamma ; REM
dol5_child_beta:            REM_BETA    rem6_saved, cursor, dol5_omega ; REM β
dol5_gamma:                 DOL_CAPTURE dol_entry_LAST, cursor, cap_LAST_buf, cap_LAST_len, subject_data, P_1_γ ; DOL γ — capture span
dol5_omega:                 jmp         seq_l0_beta ; DOL ω — child failed

P_1_γ:                      SET_CAPTURE S_FIRST, cap_FIRST_buf, cap_FIRST_len
                            SET_CAPTURE S_LAST, cap_LAST_buf, cap_LAST_len
                            jmp         L_YES_0
P_1_ω:                      jmp         L_sn_1

; ======================================================================================================================
L_sn_1:                     GET_VAR     S_OUTPUT
                            LOAD_STR    S_fail
                            FAIL_BR     L_sn_2
                            SET_OUTPUT

                            jmp         L_sn_2

; ======================================================================================================================
L_sn_2:                     GOTO_ALWAYS L_SNO_END     ; END

L_sn_3:
;  YES =================================================================================================================
L_YES_0:                    GET_VAR     S_OUTPUT
                            sub         rsp, 32
                            CONC2_VS    S_CONCAT, S_FIRST, S_SP_SL_SP
                            STORE_ARG32 0
                            lea         rdi, [rel S_LAST]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 16
                            APPLY_FN_N  S_CONCAT, 2
                            add         rsp, 32
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     L_sn_4
                            SET_OUTPUT

                            jmp         L_sn_4
L_sn_4:                     GOTO_ALWAYS L_SNO_END

L_SNO_END:
                            PROG_END


section .data
lit_str_1            db 32
lit_str_2            db 32, 47, 32
;  END =================================================================================================================

section .text

;  NAMED PATTERN BODIES ================================================================================================

; P_OUTPUT_alpha (α entry)
P_OUTPUT_alpha:             jmp         seq_l7_alpha ; SEQ
P_OUTPUT_beta:              jmp         seq_r7_beta
seq_l7_alpha:               jmp         seq_l8_alpha ; SEQ
seq_l7_beta:                jmp         seq_r8_beta

; UNRESOLVED named pattern ref: FIRST → ω
seq_l8_alpha:
seq_l8_beta:                jmp         patdef_OUTPUT_omega
seq_r8_alpha:               LIT_ALPHA   lit_str_2, 3, seq_r8_alpha_saved, cursor, subject_data, subject_len_val, seq_r7_alpha, seq_l8_beta ; LIT α
seq_r8_beta:                LIT_BETA    seq_r8_alpha_saved, cursor, seq_l8_beta ; LIT β

; UNRESOLVED named pattern ref: LAST → ω
seq_r7_alpha:
seq_r7_beta:                jmp         seq_l7_beta
;  γ/ω ---------------------------------------------------------------------------------------------------------------
patdef_OUTPUT_gamma:
                            jmp         [P_OUTPUT_ret_gamma]
;  OUTPUT ==============================================================================================================
patdef_OUTPUT_omega:        jmp         [P_OUTPUT_ret_omega]

section .text
L_END_1:  ; STUB → _SNO_END (dangling or computed goto)
                            GOTO_ALWAYS L_SNO_END
;  STUB LABELS =========================================================================================================

section .data
S_X                  db 88, 0  ; "X"
S_John_SP_Smith      db 74, 111, 104, 110, 32, 83, 109, 105, 116, 104, 0  ; "John Smith"
S_LAST               db 76, 65, 83, 84, 0  ; "LAST"
S_REM                db 82, 69, 77, 0  ; "REM"
S_LEN                db 76, 69, 78, 0  ; "LEN"
S_FIRST              db 70, 73, 82, 83, 84, 0  ; "FIRST"
S_BREAK              db 66, 82, 69, 65, 75, 0  ; "BREAK"
S_SP                 db 32, 0  ; " "
S_OUTPUT             db 79, 85, 84, 80, 85, 84, 0  ; "OUTPUT"
S_fail               db 102, 97, 105, 108, 0  ; "fail"
S_YES                db 89, 69, 83, 0  ; "YES"
S_SP_SL_SP           db 32, 47, 32, 0  ; " / "
S_END                db 69, 78, 68, 0  ; "END"
S_CONCAT             db 67, 79, 78, 67, 65, 84, 0  ; "CONCAT"
