; generated by sno2c -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o mock_engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_set_capture
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
                            PROG_INIT


;  PROGRAM BODY ========================================================================================================

                            GET_VAR     S_OUTPUT
                            LOAD_STR    S_HELLO_SP_WORLD
                            FAIL_BR     L_sn_0
                            SET_OUTPUT

                            jmp         L_sn_0
; ======================================================================================================================
L_sn_0:                     GOTO_ALWAYS L_SNO_END

L_SNO_END:
                            PROG_END

;  END =================================================================================================================

section .text
;  NAMED PATTERN BODIES ================================================================================================

section .text
L_END_0:  ; STUB → _SNO_END (dangling or computed goto)
                            GOTO_ALWAYS L_SNO_END
;  STUB LABELS =========================================================================================================

section .data
S_OUTPUT             db 79, 85, 84, 80, 85, 84, 0  ; "OUTPUT"
S_HELLO_SP_WORLD     db 72, 69, 76, 76, 79, 32, 87, 79, 82, 76, 68, 0  ; "HELLO WORLD"
S_END                db 69, 78, 68, 0  ; "END"
